### ISSUE TITLE
0.11.1 release

### ISSUE THREAD

**Issue by paultag** [hylang/hy#1009]
I'm gonna roll it in the morning; any last calls for minor bugfix only changesets?

**Comment by paultag** [comment]
cc @tianon

**Comment by tianon** [comment]
https://github.com/hylang/hy/compare/0.11.0...master It's a handy link for browsing

I don't feel like the right person to ask :innocent: 

Nothing there really jumps out at me, but I don't really understand half of it either :smile:  I know botsbuildbots fails for me in random places like the Debian tests, but not sure whether that's fixed in master or not (I see it moved to contrib at least)

**Comment by paultag** [comment]
0.11.1 released to pypi
