### ISSUE TITLE
Issue in setv expansion with dotted arguments?

### ISSUE THREAD

**Issue by jkitchin** [hylang/hy#1052]
I think there is a bug in how setv is expanded when something with a dot is used. 

Here is the example: the first setv expands like I would expect. The second one puts an extra instance of the variable in the output. Normally this wouldn't cause an issue, but it causes a bug in this SO example I think, where part of the dotted path is set to None, so the whole path is invalid.

http://stackoverflow.com/questions/35098035/how-do-i-change-the-name-of-an-xml-tag-in-hy

```
#+BEGIN_SRC hy :results python
(import os)
(setv a 5)
(setv os.path.attribute "test")
#+END_SRC

#+RESULTS:
: import os
: a = 5L
: os.path.attribute = u'test'
: os.path.attribute
```

**Comment by jkitchin** [comment]
The extra line seems to get put in here: https://github.com/hylang/hy/blob/master/hy/compiler.py#L2122

**Comment by kirbyfan64** [comment]
Not really a bug. Hy returns the result of the last expression; in this case, the attribute.

**Comment by jkitchin** [comment]
In the SO example it causes a bug. And it doesn't happen for non dotted names. Why isn't there a 5 after a=5?

**Comment by kirbyfan64** [comment]
Ah, that's definitely fishy.

**Comment by Kodiologist** [comment]
I believe the underlying bug could be titled "`setv` may try to return an lvalue that no longer exists". The issue is that in general, we allow `setv` to return its lvalue, but some assignments, such as assigning the `name` attribute of a BeautifulSoup element that we're accessing by attribute at the same time, will make the lvalue invalid.

A minimal example with BeautifulSoup is:

    (import [bs4 [BeautifulSoup]])

    (setv tco (BeautifulSoup "<meek/>" 'xml))
    (setv (. tco meek name) "defl")

This throws `AttributeError: 'NoneType' object has no attribute 'name'`. The equivalent Python doesn't produce an error, because there's no attempt to access `tco.meek.name` after the assignment:

    from hy import HySymbol
    from bs4 import BeautifulSoup
    tco = BeautifulSoup('<meek/>', HySymbol('xml'))
    tco.meek.name = 'defl'

So long as we allow `setv` to return lvalues at all, I think the only way to fix this is to make sure it only tries to do this if the user actually tries to use `setv`'s return value.

**Comment by gilch** [comment]
Python doesn't enforce any kind of consistency between `__setattr__` and `__getattr__` (or `__delattr__` or `__getattribute__`), so Hy shouldn't assume this either.

```Hy
=> (defclass Foo []
... (defn __setattr__ [self attr val]
...  (print attr val)))
class Foo:

    def __setattr__(self, attr, val):
        return print(attr, val)
=> (setv (. (Foo) eggs) 13)
Foo().eggs = 13
Foo().eggs
eggs 13
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'Foo' object has no attribute 'eggs'
```
Mutating methods in Python's standard library conventionally return `None`. Python's assignment statements, being statements, similarly have no return value. This is annoying in a Lisp, but Clojure has an elegant workaround called `doto`, which Hy has inherited.

Maybe `setv` should simply return `None`. This is much more consistent with Python. If you need to use the value in an expression, use `setv` inside a `doto`:

**Comment by gilch** [comment]
Here's another failing example:
```Hy
=> (setv (get {} 'x) 42)
from hy import HySymbol
{}[HySymbol('x')] = 42
{}[HySymbol('x')]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
KeyError: 'x'
```
This time it's asking a new dictionary for the value put in the first, which makes no sense.
