### ISSUE TITLE
Repeat behavior

### ISSUE THREAD

**Issue by brandonblock** [hylang/hy#1066]
Sorry if this is an expected behavior but repeat calling repeat on a pair of numbers doesn't return a list:

`=> (repeat 2 3)`
`repeat(2, 3)`

But when the result of repeat is used by another function, the behavior is as expected (albeit which argument is the value and which is the number of repeats is reverse of clojure and that threw me for a bit—I actually prefer it this way):

`=> (reduce * (repeat 2 3))`
`8`

**Comment by gilch** [comment]
This is expected. Hy's `repeat` is not based on Clojure's but is simply an import of [Python's repeat](https://docs.python.org/3.5/library/itertools.html#itertools.repeat) from the standard `itertools` module. Technically, Clojure's repeat doesn't return a `list` either, though objects supporting the `seq` protocol are printed that way by default. Python's printed representation has the advantage of terminating even when the iterable is infinite. You can show its contents by constructing a tuple with it, like so:
```Hy
=> (tuple (repeat 2 3))
(2, 2, 2)
```
Don't do this with an infinite iterable or the `tuple` constructor will never return!

The difference in argument order is due to the difference in the way Clojure and Python handle default arguments. Clojure functions can have overloaded arity, so completely different functions may have the same name, as long as they have a different number of arguments. Hy has experimental support for this style in a contrib module.

Python (and thus Hy), on the other hand, behaves more like Common Lisp where some arguments are optional because they have default values, but they must appear after the required arguments. In both Clojure and Python, `repeat` can be called with one argument to repeat the element infinitely. Since the element to be repeated is not optional, it must come first in Python.

You can use `=> (help repeat)` to display its Python docstring, and information about its arguments and so forth. This is a feature of Python, not Hy, so some Hy features (like macros) with docstrings don't work with `help` yet. This is similar to `(doc repeat)` in Clojure.

**Comment by brandonblock** [comment]
Thanks for the excellently informative answer!
