### ISSUE TITLE
Question: setv with quoted values?

### ISSUE THREAD

**Issue by Jiehong** [hylang/hy#1079]
Hello,

I was playing with the language, and then I wanted to try to write 2 equivalent expressions, but that didn't work:

```
(setv a 3) # valid
(set 'a 3) # set doesn't exist, and this is invalid
```

I guess I imagined that `setv` was a sort of `setq`, thus I wanted to try to write the quoted form myself…

Do you know if writting something similar is possible?

**Comment by kirbyfan64** [comment]
Not easily. AFAIK Python disallows a lot of stuff like this due to the way its internals work, therefore making it really hard for Hy to do anything about it.

**Comment by gilch** [comment]
`set` does exist, but it doesn't do that--it makes `set` objects:
```Hy
>>> (set [1 2 2 1 2])
{1, 2}
```
Assignments to function locals in Python must be defined at compile time due to optimizations. (There's a workaround, but it was removed in Python 3). You can, of course, create a dictionary as a local and use whatever symbols you want in that. Python does let you compile new functions at runtime in various ways. Hy can also expand macros into function definitions.

Assignments to other namespaces don't have this limitation though. Normal classes, modules, and other instances are backed by a simple dictionary. There are exceptions, see `__slots__` and `__prepare__` in the Python docs. See also `vars`, `globals`, and `setattr` for how to use these instance dictionaries.

**Comment by Jiehong** [comment]
Let me try to understand that clearly.

Away from hy, in another lisp, I'd expect the following:

``` lisp
(set a 1)
; This is read as a list
; Evaluated with 'set' as a function, fail if doesn't exist
; Then 'a' is evaluated, and this would fail as 'a' is unassigned yet (void variable)
(set (quote a) 1)
; Same as before, but the 'quote' macro would evaluate to the symbol 'a'
; Then the set would finish correctly and 'a' would be equal to 1 after this line
(set 'a 1)
; Ok, same, but the read pass will convert this to the previous form, so it's identical.
```

Trying to look in the code of hy, `setv` seems to be defined in compiler.py, and is thus a 'native' construct of the language, dropping the need for quoting for the variable.

What was the intend behind this when `setv` was conceived? I'm just being curious.

Correct me if I'm wrong though.

**Comment by kirbyfan64** [comment]
@Jiehong Like @gilch said, Python simply doesn't allow you to easily assign a variable *known at runtime*. It's not as much a voluntary "hey, we should do this" as it being the only way on Python 3.

**Comment by Jiehong** [comment]
I simply wanted to reformulate on my own here :)

Thanks for this nonetheless!

**Comment by paultag** [comment]
So I think the core misunderstanding is that we compile to Python bytecode, by way of Python's AST (Python's syntax), we don't do anything fancy, really.

So, when we say `(setv foo 1)`, that translates into Python bytecode literally:

```hy
=> (dis.dis (fn [] (setv a 1)))
  1           0 LOAD_CONST               1 (1)
              3 STORE_FAST               0 (a)
              6 LOAD_FAST                0 (a)
              9 RETURN_VALUE
```

This is the same as running `a = 1` in Python.

So the simple implementation is "Well, why don't we just write to `locals` or something?". The issue here is that `locals()` is something you can't write to in a program (but you can in a REPL :) )

If that was to work, the issue is now handling weird edge-cases `a["foo"] = baz`, globals, nonlocals (although I *think* we could ignore globals and nonlocals for now?), but it could be tractable.

It's mostly an issue where once again, we have to break on the lisp-y-ness of Hy in order to make a pragmatic choice about what our end goal is.

So, neat bug, love the idea, and solving it would be a really neat hack, that we could use in loads of places :)
