### ISSUE TITLE
cond should accept single-argument branches

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1084]
In Common Lisp, the result of the test itself is the result of the `cond`, if an alternative is not provided:

``` Lisp
* (cond (:foo))

:FOO
```

In Hy it's an error.

``` Hy
=> (cond [:foo])
  File "<input>", line 1, column 7

  (cond [:foo])
        ^----^
HyMacroExpansionError: b'cond branches need at least two items: a test and one or more code branches'
```

It needn't be.

**Comment by kirbyfan64** [comment]
What exactly would be the use case, though? This almost seems kind of random...

**Comment by tuturto** [comment]
With Python's truthiness and collections this could be useful. I imagine it would be used similar to ```ap-if```

```hylang
(cond [coll]
  [true []])
```
would be equivalent to

```hylang
(ap-if coll it
  [])
```

Both would return ```coll``` if it's a non-empty collection. Otherwise an empty list would be returned.

Another idea is to return first true value returned by a group of functions (although one could build this with a list of functions and some ```map``` + ```filter``` and then process wouldn't be so hard-coded):

```hylang
(defn translate-account-number [acc-id]
  (cond [(translate-finnish-account acc-id)]
    [(translate-swedish-account acc-id)]
    [(translate-norwegeian-account acc-id)]
    [true (raise-error "Unknown format")]))
```

This function would take an account id, try to use three different translation methods and return result of first succesful translation (each function would return ```nil``` if they can't perform translation). In case no translation is possible, an error is raised.
