### ISSUE TITLE
All shadowed operators should have the same arities as their counterparts.

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1104]
Probably one of them got updated without the other:

``` Hy
=> (+)
0
=> ((lambda [op] (op)) +)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<input>", line 1, in <lambda>
  File "c:\users\me\code\repos\hy/hy/core/shadow.hy", line 27, in +
    (defn + [&rest args]
  File "c:\users\me\code\repos\hy/hy/core/shadow.hy", line 31, in _hy_anon_fn_1
    (raise (TypeError "Need at least 1 argument to add/concatenate"))
TypeError: Need at least 1 argument to add/concatenate
```

We should check them all though.

**Comment by Kodiologist** [comment]
I noticed when I was reading hy.core.shadow this weekend that `+` demands an argument but `*` doesn't. That is, we provide the empty product but not the empty sum. I thought about it and realized that the problem with nullary `+` is that Python uses `+` for both addition and concatenation, so in a nullary context, we should return `[]`, `()`, `""`, or `0`, but we can't know which. It seems best to just disallow nullary `+`. So I think the shadowed version is right and the operator version is wrong.

For `/`, there's again inconsistency between the operator (which returns `1.`) and the shadowed version (which requires two arguments). It's not clear which is right, though. I'm leaning towards requiring the arguments, because although `1.` is the only sane value for the "empty quotient", I can't think of a context where asking for an empty quotient wouldn't be a mistake.

For `-`, the operator and shadowed version both require an argument, which seems fine, but not consistent with allowing nullary `/` if we decide to keep doing that.

Here's what some other Lisps do for `-` and `/`:

- In Clojure and Common Lisp, both `-` and `/` require an argument. Unary `/` is allowed, and returns the reciprocal.
- In Emacs Lisp, nullary `-` returns 0, but nullary `/` isn't allowed. Unary `/` returns its argument unchanged.

I think we should follow Clojure and Common Lisp. (We already have unary `/` return the reciprocal.)

**Comment by gilch** [comment]
>I thought about it and realized that the problem with nullary `+` is that Python uses `+` for both addition and concatenation, so in a nullary context, we should return `[]`, `()`, `""`, or `0`, but we can't know which. It seems best to just disallow nullary `+`. So I think the shadowed version is right and the operator version is wrong.

You could make the same argument against `*`. It also works on strings, tuples, and lists:
```Hy
=> (* 3 "1")
'111'
=> (* 3 [1])
[1, 1, 1]
=> (* 3 (, 1))
(1, 1, 1)
```
In fact, any class can implement operators using dunder methods.

I don't think that's a good reason to disallow nullary `+`. Look at what ClojureScript does:
```Clojure
cljs.user=> (+ "a" "b")
"ab"
cljs.user=> (+)
0
```
I'm inclined to do things Clojure's way when Python doesn't object.

**Comment by Kodiologist** [comment]
> You could make the same argument against `*`.

The difference is that 1 is the identity element for both uses of `*` (multiplication and replication), whereas 0 isn't the identity element for concatenation.

What do you think about the cases of `-` and `/`?

**Comment by gilch** [comment]
That's a fair point. But every Lisp I've asked says `(+)` is `0`, including ClojureScript, which uses `+` for more than numbers. I think that's good enough. We could conceivably create an additive identity singleton that returns whatever it's added to and have `(+)` return that, similarly for `(*)`. But then does it break when you use other operators that `0` understands? Maybe it could be a special case of `0` the same way `false` is. I'm not sure it's worth the trouble.

I don't know why nullary `/` is allowed in Hy. That doesn't really make sense. @kirbyfan64, was this a mistake when you added the unary reciprocal case I asked for? If so, we should probably remove it. If there's an argument for it I'd like to hear it, since it may also apply to `-`.

**Comment by Kodiologist** [comment]
Yeah, I think you've convinced me. Let's keep nullary `+` returning 0, and make the shadowed version consistent.
