### ISSUE TITLE
[feature] Allow selective macro import

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1118]
This is related to #277, but (I think) substantially less ambitious.

Right now, the only way macros from another file or module can be included is with `(require foo)`, which imports all macros defined in the module `foo`. So there are all the usual namespace-pollution perils of `(import [foo [*]])`: `foo` might have a macro added to it that happens to have the same name as something in the importing module. The risk of breakage is even greater than with `import` because ordinarily imported variables can be overwritten by ordinary assignments, whereas macros take precedence over ordinary assignments. Hy doesn't even have a warning for a macro shadowing a function.

To fill this gap, I propose a feature that I think will be pretty easy to implement. Analogous to `(import [foo [a b]])`, we should allow `(require [foo [a b]])`, which imports the macros `a` and `b` but nothing else (and throws an error if `a` or `b` isn't a macro available for import).

To make the syntax of `require` more consistent with `import`, we might also make `(require [foo [*]])` mean what `(require foo)` currently means, and make `(require foo)` raise a deprecation warning, so that later we can have it import macros named `foo.a`, `foo.b`, etc., like `(import foo)` does for ordinary names.

**Comment by gilch** [comment]
Yeah, I'm inclined to agree that's a problem. 

I'm not sure yet of that solution, but it seems reasonable at a glance. I'd like to look deeper at how Hy's macros are implemented, maybe treating them as living in modules isn't appropriate, and something like Clojure namespaces is better. Someone more familiar with that part of Hy's internals might have more to say about it.

I'm not sure I'd bother with the deprecation warning at this time, since we're breaking everything for the Grand Language Cleanup anyway.

**Comment by tuturto** [comment]
Closed by 14fddbe
