### ISSUE TITLE
Hy loses a method name in certain uses of defclass

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1150]
The following code:

    (defclass A []
      [m1 (fn [self]
        1)]
      [m2 (fn [self]
        2)])
    (setv a (A))

    (print (.m1 a))
    (print (.m2 a))

raises `AttributeError: 'A' object has no attribute 'm2'`. hy2py shows that it gets translated to this:

    class A:

        def m1(self):
            return 1

        def _hy_anon_fn_2(self):
            return 2
    a = A()
    print(a.m1())
    print(a.m2())

Somehow the name `m2` got lost. We should see either `def m2` or `m2 = _hy_anon_fn_2`.

This bug doesn't arise if you use only one pair of square brackets for both methods.

**Comment by gilch** [comment]
Your expectations don't meet the specification for `defclass`. The first `[]` is for superclasses, the second is supposed to be like a `setv`, and the third should just be a normal `HyList`.

I argued against treating the second `[]` specially, #850 since a `setv` would do here and is closer to the way Python works. 

That said, the `hy2py` output doesn't seem to meet the spec either. The HyList you created might have a side effect and thus should appear in the class definition. I don't think the compiler could possibly be smart enough to omit this only when it doesn't matter.

`defclass` needs some work to get metaclasses working properly anyway. Python 2 and 3 handle this very differently.

**Comment by Kodiologist** [comment]
Ah, I had no idea how `defclass` is actually supposed to work. Feel free to rename this issue if you can think of a better description.

**Comment by kirbyfan64** [comment]
@gilch What if, for metaclasses, we went the Python 3 route:

```hy
(defclass X [:metaclass Y] ...)
```

**Comment by gilch** [comment]
@kirbyfan64, I agree that's how it should work when Hy targets Python 3. It will cause fewer problems if Hy uses the exact same keyword as Python, since metaclasses are free to use any other keyword arguments.

@algernon's first pass at this #887 used the `:meta` keyword instead. I think that's misguided, since there are better ways to avoid typing a few extra characters that don't make Python compatibility more difficult. For example, you could do something like this in Python:
```Python
from mystuff import my_metaclass, args, kwargs, Baz


def mc(a_metaclass):
    return dict(metaclass=a_metaclass)


class Foo(Baz, *args, **kwargs, **mc(my_metaclass)):
    ...
```
I think Hy needs something similar to Python's multiple `**` and `*`. #1128. Hy also has macros to help with this kind of thing.

I don't think it will be easy to backport this to Python 2 though. It wouldn't be the first Hy feature that depends on the underlying Python version. I think the Python 2 metaclass syntax already works, but only when targeting Python 2, of course. I already think supporting Python 2 is more trouble than it's worth, and this will only become more true over time.

With a metaclass, a class declaration doesn't have to "return" (i.e. assign to the class name--it's a statement, not an expression) an actual class. It could be any type of object. Python libraries may (ab)use this feature, and Hy needs to support that.

**Comment by kirbyfan64** [comment]
@gilch Why not just automatically detect the `metaclass` keyword and then set the `__metaclass_` attribute?

**Comment by gilch** [comment]
You could do that, but it wouldn't be enough. I don't think it's worth the trouble. They completely redid the metaclass system for Python 3.

Would you also do the reverse, and set a `:metaclass` keyword argument when the attribute is detected? A macro could do that, but _only if it could be determined at compile time_, since a metaclass call happens before the class body is executed. It's not worth it. Python 2 also lets you set a `__metaclass__` attribute at the module level. Python 3 doesn't have a good equivalent. Injecting it into the whole module would be tricky even with macros, and it still only works at compile time.

Python 2's metaclasses are much weaker than Python 3's. You can do pretty much everything a Python 2 metaclass does with a class decorator. Python 3 can do this much, but also gives you a deeper hook. A metaclass can prepare the class dictionary _before_ it executes the class body. You could, for example, use an `OrderedDict` instead and preserve the order of all assignments in the class body. If you're using a class declaration to represent something other than a class (like an XML file, say), this ordering might be important information. You could instead create some kind of custom dict class and declare multiple methods (or other attrs) with the same name in the class body. The custom dict could save all of them. In Python 2, they'd get overwritten before the metaclass can get to them and you'd only see the last one.

There are ways to approximate these capabilities for any given use case in Python 2, but you'd have to write the class declaration differently to avoid losing information. Making this work the same way in Hy targeting Python 2 and 3 seems really difficult without spawning a bunch of weird edge cases, and if we can't do that, why bother going halfway?

**Comment by Kodiologist** [comment]
This shouldn't really be an issue with the new special-form parsing.
