### ISSUE TITLE
Lvalue of setv is checked too early when using `or`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1151]
This is a subtopic of the dreaded #233 that I think should have been fixed by #824. Consider the code:

    (import [random [random]])
    (setv x (or (< (random) .5) (do (setv y 1) y)))

This gets translated to:

    from random import random
    _hy_anon_var_1 = (random() < 0.5)
    if (not x):
        y = 1
        _hy_anon_var_1 = y

so running it raises `NameError: name 'x' is not defined
`.

For what it's worth, back in 0.11.1, the result would've been:

    from random import random
    y = 1
    x = ((random() < 0.5) or y)

which is wrong because we aren't even attempting the short-circuit.

**Comment by gilch** [comment]
I've developed a macro that appears to do the right thing. See if you can break it. If it's all working properly this is a good starting point for what the AST should look like.
```Hy
=> ;; hy --spy

=> (defmacro -or (&rest args)
...   (if (empty? (cdr args))
...       (first args)
...       (do
...         (setv g (gensym))
...         `(do
...            (setv ~g ~(first args))
...            (if* ~g
...                 ~g
...                 (-or ~@(cdr args)))))))
from hy.core.language import first, gensym, is_empty
import hy
from hy import HyExpression, HySymbol

@hy.macros.macro('_or')
def _hy_anon_fn_1(*args):
    if is_empty(args[1:]):
        _hy_anon_var_1 = first(args)
    else:
        g = gensym()
        _hy_anon_var_1 = HyExpression(((([] + [HySymbol('do')]) + [HyExpression(((([] + [HySymbol('setv')]) + [g]) + [first(args)]))]) + [HyExpression((((([] + [HySymbol('if*')]) + [g]) + [g]) + [HyExpression((([] + [HySymbol('_or')]) + list(args[1:])))]))]))
    return _hy_anon_var_1
=> (import [random [random]])
from random import random
=> (setv x (or (< (random) .5) (do (setv y 1) y)))
_hy_anon_var_1 = (random() < 0.5)
if (not x):
    y = 1
    _hy_anon_var_1 = y
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'x' is not defined
=> (setv x (-or (< (random) .5) (do (setv y 1) y)))
:G_1235 = (random() < 0.5)
if :G_1235:
    x = :G_1235
else:
    y = 1
    x = y
=>
```
We _could_ just use the macro, honestly. The choice of true special form vs. macro makes little difference to the end user, but I think the built-in version can be more efficient, since it can compile to Python's `or` in some cases and avoid wasted assignments.

**Comment by Kodiologist** [comment]
Very nice! I'll give it a closer look tomorrow. Don't forget about the 0-argument case. Have you tried it against the `or` tests we already have?

While using the native `or` when possible is nice, it's not a big deal, in my opinion. It's not even obvious to me that it would actually be faster.

**Comment by gilch** [comment]
The nullary case works:
```Hy
=> (or)
None
=> (-or)
None
```
I didn't test it that way, but it's probably a good idea to use the existing tests. I'm not sure how easy that would be. I wonder if the tests would just work if you changed the macro name from `-or` to `or`. (Don't forget to rename the recursive part). You might want to disable compilation of `or` just to be sure we're testing the right thing, but that would break the world, so you'd have to define the macro pretty early. (i.e. actually implement the macro version in Hy) Maybe it's easier to just do a find and replace in the tests and keep the name `-or`.

The performance difference might not be noticeable most of the time, but there is a gensym assignment statement that isn't always necessary:
```Hy
=> (or 1 2)
(1 or 2)
1
=> (-or 1 2)
:G_1235 = 1
(:G_1235 if :G_1235 else 2)
1
```
See the difference?

@kirbyfan64, you implemented the current `or` version, is this an easy fix?

**Comment by gilch** [comment]
The three argument case makes the difference even more obvious:
```Hy
=> (or 0 1 2)
(0 or 1 or 2)
1
=> (-or 0 1 2)
:G_1236 = 0
if :G_1236:
    _hy_anon_var_1 = :G_1236
else:
    :G_1237 = 1
    _hy_anon_var_1 = (:G_1237 if :G_1237 else 2)
```
Now that I think about it, I'm not sure we could reasonably detect the cases were a gensym isn't required. Correctness outweighs performance. 

Python's expression/statement distinction just make things awkward. Python _requires_ local assignments to be statements. We could use a method call expression to set a dict item or attr instead, but that's less efficient than a local.

More reasons to use a special form instead of a macro if we can: 
* `(macroexpand)` output may be a bit prettier, 
* and similarly, `hy --spy` output is more readable when we can use Python's `or`.
* If future Python versions expand on the uses for the `or` word (as they've done for other reserved words in the past), it could be a problem if Hy can't output a Python `or`. Maybe we could have a binary-only `or*` for that, but statements are still awkward, so I'm not sure that helps. I guess we can cross that bridge if we come to it.

These are not very strong reasons though. A lot of other Hy forms aren't pretty when compiled.

**Comment by Kodiologist** [comment]
Turns out that we only have a few `or` tests already, in native/language.hy, and they do pass when I replace `or` with `-or`. But I found a case that fails:

    (print (list-comp (-or (< x 5) (foo)) [x (range 10)]))

This compiles to:

    :G_1235 = (x < 5)
    print([(:G_1235 if :G_1235 else foo()) for x in range(10)])

If we replace `-or` with `or`, we get:

     print([((x < 5) or foo()) for x in range(10)])

Arguably, this is more of a bug (or unavoidable Python limitation) in `list-comp` than `-or`. List comprehensions are always going to be second-class citizens in Hy compared to `filter` and `map` (short of automaticallly generating intermediate functions, or compiling `list-comp` to `map` and `filter` instead of a real list comprehension), because Python doesn't permit statements in them. So I'm inclined to just let this break.

I think we should make a PR using this macro, or a `HyASTCompiler` method based on it, and using something similar for `and`. Would you like to do it, or shall I?

**Comment by kirbyfan64** [comment]
Huh...here's a smaller test case:

```hy
(setv x (or z (do y y)))
```

Can I have a few moments to look into this a bit more first? This just seems really, really bizarre, and I'm curious as to why the heck this is happening.

**Comment by Kodiologist** [comment]
Knock yourself out.

**Comment by kirbyfan64** [comment]
#1152

**Comment by gilch** [comment]
>Arguably, this is more of a bug (or unavoidable Python limitation) in list-comp than -or. List comprehensions are always going to be second-class citizens in Hy compared to filter and map (short of automaticallly generating intermediate functions, or compiling list-comp to map and filter instead of a real list comprehension), because Python doesn't permit statements in them. So I'm inclined to just let this break.

Well I'm not okay with this. I'd sooner remove `list-comp` and friends than keep the current surprising behavior. I don't see how compiling to `map` and `filter` helps though. See #588.

**Comment by Kodiologist** [comment]
Not really a problem for this issue, since #1152 doesn't create the bug I described.
