### ISSUE TITLE
`let` can lead to avoidable unbound local error

### ISSUE THREAD

**Issue by Marrin** [hylang/hy#1212]
On the surface this might look like #664 but this would be easily avoided if `let` is implemented closer to Lisp (or was it Scheme?)

```clojure
(defn test [x]
  (let [x (inc x)]
    (print x)))
```

Compiled to:

```python
def test(x):
    def _hy_anon_fn_1():
        x = inc(x)
        return print(x)
    return _hy_anon_fn_1()
```

But as I recall `let` in List/Scheme being just a transformation to a anonymous function immediately called I expected *this* as equivalent Python code:

```python
    def test(x):
        def _hy_anon_fn_1(x):
            return print(x)
        return _hy_anon_fn_1(inc(x))
```

That doesn't have the unbound local problem. Why isn't `let` transformed this way?

**Comment by Kodiologist** [comment]
I'm going to bump up removing `let` entirely (#1056) on my to-do list. I think we should've done that a long time ago.

**Comment by kirbyfan64** [comment]
Come to think of it, is there a reason we're not compiling `let` into just:

```hy
(let [x 1] (stuff) x)  ->  (do (setv x 1) (stuff) x)
```

I know `x` still stays in scope, but in general Python doesn't have any blocks that open up new scopes.

**Comment by gilch** [comment]
Yes, there are reasons, and we've discussed them before, remember? #1056

The first reason is that the `do` block has no [lexical closure](https://en.wikipedia.org/wiki/Closure_(computer_programming)), while the current function version does. In Clojure and Common Lisp, `let` also does. If we have a `let` that doesn't work right we can't fix it later on without breaking API. If we eliminate `let` early, we still have the option of adding it later.

Leaking into the local scope is only a minor problem, since Hy automatically creates local `_hy_anon_var`s anyway. Python 2's list comprehensions also "leaked" and in most cases this didn't cause problems. If it happens in a function, it's scope is pretty limited anyway. It's a bit more of a problem at the module level. You can use `del` to clean it up though.

The other reason is that if you nest `let`s, an inner variable with the same name should shadow the outer one. This even works in dynamically scoped lisps with no lexical closures like emacs. The `do/setv` implementation would just overwrite it. Nesting also works now in the current function-based `let`.

But the current function-based `let` also has severe problems. It breaks `async/await`, `break/continue`, and `yield`. We'd just be trading one set of problems for another. The right solution seems to be to eliminate `let`.
