### ISSUE TITLE
allow keyword arguments without values, defaulting to True

### ISSUE THREAD

**Issue by philiparvidsson** [hylang/hy#1213]
I'm writing this as a suggestion—I'm unsure of the implications so this issue shall be seen as merely lifting the idea up for discussion.

Often, functions take a keyword argument with a boolean value, indicating whether a feature should be enabled or not. For example, consider:

```python
defn write_to_file(filename, text, append=False):
    # ...
```

In Hy, we can call the function like this:

```lisp
(write-to-file "foo.txt" "hello world" :append True)
```

The `True` keyword seems redundant here, and it would possibly be more neat to call it in the following manner:

```lisp
(write-to-file "foo.txt" "hello world" :append)
```

Would this be possible and feasible to implement?

**Comment by kirbyfan64** [comment]
Nice idea, but it has a bit of potential for confusion. Since Hy allows positional arguments to come after keyword arguments, you end up with some ambiguity. If someone writes:

```hy
(func :a 123)
```

do they mean to set `:a` to `True` and also pass `123`, or set `:a` to `123`.

**Comment by philiparvidsson** [comment]
Perhaps it could be combined with some other character denoting it to be a boolean defaulting to true. Some ideas:

```lisp
(func :a? 123)
(func :a. 123)
```

**Comment by Kodiologist** [comment]
See also #1119. What I do these days is use `(setv T True  F False)` so I can write, e.g., `(func :a T 123)` or `(func :a F 123)`.

**Comment by gilch** [comment]
Python is duck-typed. `False` is a special case of `0`, and `True` a special case of `1`. Hence:
```
>>> False + True
1
>>> False * True
0
>>> 41 + True
42
```
You can just as easily use `1` and `0` instead of `True` and `False`, (e.g. `:a 1`) which is just one character longer (the space) than your proposed `:a?` or `:a.` Whether this is good style is a different question, but it's arguably better than `(def T True F False)`, since it's more standard. Early versions of Python didn't even have a bool type (see [PEP 285](https://www.python.org/dev/peps/pep-0285/)), so this almost always works.

The `:a?` suggestion has another problem: `:a?` is already a valid keyword in Hy. You can define a function now that takes such a keyword argument.

I would prefer to keep Hy's compiler as simple as is reasonably possible, rather than adding special cases that could just as easily be implemented as a (reader) macro in a library. I'm more inclined to add features if they're already present or Clojure, since Hy's syntax is heavily based on Clojure, and very willing to add features already in Python, since we're trying to maintain compatibility with Python.

**Comment by Kodiologist** [comment]
> You can just as easily use `1` and `0` instead of `True` and `False`

There's nothing preventing a function from treating `True` differently from `1`, and indeed this happens pretty often.

**Comment by gilch** [comment]
@Kodiologist that is true, and enabling that distinction is why bool types were added to Python in the first place. But in the case we were discussing viz. "Often, functions take a keyword argument with a boolean value, indicating whether a feature should be enabled or not.", a `0` or `1` nearly always works.

The distinction might be more important for adding a bool type in a database rather than an integer type, one of the cases mentioned in the PEP. But in such cases I think it's usually better style to spell out `True` and `False` explicitly.
