### ISSUE TITLE
Lists and the functional functions

### ISSUE THREAD

**Issue by refi64** [hylang/hy#1247]
Crappy title, I know. Moving on.

Right now, all the high-level sequence-processing functions (e.g. `map`, `filter`) return an iterator. This is fine in Python, where these are rarely ever used anyway. But in Hy where everything is a bit more functional, things get messy.

Of course, there are still use cases for the iterable return value, too.

**Comment by kirbyfan64** [comment]
...and I didn't mean to hit "Submit" yet. Dammit, Android!!!!

*Anyway*, I have a couple of ideas:

- Make all the functions return something like @gilch's `seq`. Problem: it's not an iterator, but it still isn't a list. Even if fancier things like lazy concatenation were to be added, it still wouldn't work when you try to pass it to something expecting a list.

- Implement a list subclass that behaves like a "lazy list". Problem: I have a feeling that behaving like a list but being lazy would give some really surprising behavior from time to time.

- Create anaphoric functions. Problem is, sometimes you still don't want a list.

- Create a reader macro for making a list. My personal favorite choice, since everything stays normal, but now you don't have to put all the long list conversions.

I would love a mix of the first and last points, personally.

**Comment by Kodiologist** [comment]
The last idea is just shorthand for `(list ...)`, right? Were you thinking of anything in particular? Perhaps `#l`, so that

    (list (map inc [1 2 3]))

could be written

    #l(map inc [1 2 3])

**Comment by egregius313** [comment]
In the case of `map` could we consider adding something like Clojure's `mapv` and have that essentially be `(compose list map)`?

**Comment by Kodiologist** [comment]
How is Clojure's `mapv` different from Python's `map`?

**Comment by egregius313** [comment]
`mapv` returns a vector instead of a seq. So in Hylang, `mapv` would return a list. It would be equivalent to Python 2's `map`.

**Comment by Kodiologist** [comment]
Oh, I see.

For what it's worth, I usually use a macro I wrote called `amap`, which is both anaphoric and always produces a list. It turns out to be pretty rare that an existing named function does exactly what I need, and I usually want a list at the same time.

**Comment by Kodiologist** [comment]
Looking at this from 2022, it's clear that we don't want to shadow the native `map` and `filter`, although we can provide substitutes. And we do: Hyrule has an anaphoric version of each (which produce iterators like the Python versions), and it has a lazy-list-like type, namely `Sequence`. Probably the most convenient option is `lfor`, which can readily be swapped out for `gfor` when you actually do want an iterator.

We don't have a tag macro for calling `list`, if only because you would usually use `lfor` instead, but it's a one-liner if you want it. If somebody still thinks it should be in Hyrule, that's an option, but I doubt there's interest.
