### ISSUE TITLE
The anchoring to the section of the `.` symbol is faulty.

### ISSUE THREAD

**Issue by yuvallanger** [hylang/hy#1275]
You cannot use `#.` [1] or `#%2E` [2] in the link. Using the name of the `.` symbol would probably solve the problem.

[1]: <https://github.com/hylang/hy/blob/18acfe6495e83dccc9c0f3ddf105dc7ccef5a86a/docs/language/api.rst#.>
[2]: <https://github.com/hylang/hy/blob/18acfe6495e83dccc9c0f3ddf105dc7ccef5a86a/docs/language/api.rst#%2E>

**Comment by Kodiologist** [comment]
In the HTML, the section is given an empty `id`:

    <h3><a id="" ...

This looks like a bug in how GitHub renders reStructuredText. By contrast, Read the Docs creates an ID `id1`: https://hy.readthedocs.io/en/latest/language/api.html#id1 . So does Sphinx, which is what we use when you do `make docs`.

Since this seems to be GitHub's bug, I'm going to close this issue, but feel free to report it to them.
