### ISSUE TITLE
Ugly error message when third argument of dict-comp isn't a HyList

### ISSUE THREAD

**Issue by hrehfeld** [hylang/hy#1277]
https://gist.github.com/hrehfeld/631b367babaf93f1bf6b66a62fe2276e

hy 0.12.1+70.gad94343

**Comment by kirbyfan64** [comment]
Reminds me of #634. Sometimes I wonder if it'd be worth it to have a giant mono-issue just dedicated to missing checks. (IIRC `genexpr` might have had some missing checks, too.)

Also, wow, that was a looong time ago!

**Comment by hrehfeld** [comment]
Should I continue to report instances of stuff like this? I don't want to spam the issues, but it might be worth it for the debugging info?

**Comment by Kodiologist** [comment]
That's not a bad idea, Ryan. Also, the right way to handle these problems is probably not to write explicit checks for every case but to implement a concise way to declare the right syntax, which automatically produces a sane error message.

@hrehfeld If you're not sure whether to report a given bug, you could [send me an email](http://arfer.net/elsewhere) instead of creating an issue.

**Comment by kirbyfan64** [comment]
Or contact the mailing list.

**Comment by Kodiologist** [comment]
The equivalent error message is cleaner now, albeit not terribly informative.

```
=> (dfor  a [1 2 3]  a)
Traceback (most recent call last):
  File "stdin-9ab68580f8e0a31fe22e82c79896a834d427e921", line 1, in <module>
    (dfor  a [1 2 3]  a)
  File "<stdin>", line 1
    (dfor  a [1 2 3]  a)
                      ^
hy.errors.HySyntaxError: parse error for special form 'dfor': got unexpected token: end of form
```
