### ISSUE TITLE
Alternative syntax for string literals

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1287]
Along the lines of #1042, or at least @gilch's reply to himself, I'd like to give Hy another syntax for string literals. Currently we only support double-quoted strings, which is inconvenient when the string itself contains lots of double quotes, or you're writing Hy code as part of a shell command and hence are running out of quote characters fast. We could adopt Python's triple-quoted strings (with double quotes), but six characters of delimiters (seven if you want a raw string) is pretty bulky for a string literal, and this doesn't help at all if you're embedding the code in a double-quoted string. Here are three proposals. @kirbyfan64, @tuturto, what do you think?

**Proposal A**

Permit delimiting string literals with `«` and `»`. This would work identically to double quotes, except now it's `»` rather than `"` that needs to be escaped.

**Proposal B**

Permit beginning string literals with `#` followed by a backtick and ending them with another backtick. Again, this works just like double quotes.

**Proposal C**

I propose something inspired by Perl's `q` operator, but a little simpler. A literal of this form begins with `#qC`, where `C` is any character that isn't whitespace or `;`. It ends with another instance of `C`, unless `C` belongs to the Unicode General Categories Ps (Punctuation, open) or Pi (Punctuation, initial quote), in which case the character with the code point after `C` terminates the literal.

These literals are always parsed as raw strings, and interpreted as Unicode strings (`unicode` on Python 2, `str` on Python 3) rather than bytestrings.

Here are some examples:

- `#q!Hello, world.!`
- `#q(Hello, world.)`
- `#q"Hello, world."`
- `#q'Hello, world.'`
- `#q("It's okay." he said.)`
- `#q( ;; This is a string, not a comment. )`
- `#q{Curlies}`
- `#qXHow about letters?X`
- `#q«ASCII is for “small minds”.»`
- `#q)This is allowed, but stupid.)`
- `#q(The backslash in \n is preserved)`.

And also:

    #q(Literal newlines
    are allowed, and preserved.)

They produce an ordinary `HyString`.

**Comment by kirbyfan64** [comment]
- Proposal A: -1. Unicode characters are hard enough to type already...
- Proposal B: Ehh...I mean, it kind of makes sense, but it's also kinda weird. +-0
- Proposal C: ...I kind of like this one, but a bit cautiously...so...+0.5?

Personally, I don't mind Python's triple-quoted string literals, though, because they fit in pretty well with the rest of the language. They make logical sense in the context of everything else, and *they wouldn't require barring off another possible character from sharp macros*.

**Comment by Kodiologist** [comment]
That's a lot of italics; is it very important that `#q` be free for the user to define?

**Comment by gilch** [comment]
> Perl's q operator, but a little simpler. 

> unless `C` belongs to the Unicode General Categories Ps (Punctuation, open) or Pi (Punctuation, initial quote), in which case the character with the code point after C terminates the literal.

There's no point in supporting paired delimiters like that unless you can also nest them like Perl does. All or none.

> Personally, I don't mind Python's triple-quoted string literals, though, because they fit in pretty well with the rest of the language. They make logical sense in the context of everything else, and *they wouldn't require barring off another possible character from sharp macros.*

That was Python, this is Hy. Hy is already using `'` for the `(quote)` form. Sometimes you need a quoted quote in macros, so `'''` is also out. That just leaves `"""` which just isn't good enough by itself because sometimes you need a triple-quoted string in a doctest. Hy can't do it Python's way and still look like a Lisp.

If we had tagged literals #1046, I'd be less reluctant to give up another character. I'm also not sure how I feel about calling them "sharp macros" since the "sharp" character `♯` is distinct from the "number sign" `#` that we actually use. (I don't want them called "number-sign macros" either.)

I also like Proposal C best so far, but don't think it's good enough. Let's consider the actual use cases our current strings aren't meeting adequately.

### doctests

If any of the code in the doctest has a `"` character (a common occurrence), it must be escaped. Proposal C is an improvement here, but still falls short.

You have to pick a character you're not allowed to use, and might have to change it as you edit the string. This seems like a pain. Python's triple quotes are easier in this regard: no single character can end the string.

Given the sheer number of Unicode characters, any doctest of reasonable length will omit some, so you can quote any reasonable doctest without escapes. But I don't want to force Hy programmers to use characters they can't type on a standard US keyboard, or save in a plain ASCII file. This is also the main reason I rejected Proposal A.

### regex
Sometimes you need a `"` and `'` in a regex. You also need `\` for nontrivial regexes. Python's raw triple quotes are great for this. Clojure's regexes look like `#"this"`. Hy doesn't have a built-in literal (since Python doesn't), but a reader macro helps, and this was [specifically mentioned in Hy's docs](http://docs.hylang.org/en/latest/language/readermacros.html?highlight=regex). How should a regex look under these proposals? Like `#^#q/"don't"/`?

### new literals

If we had proper Common-Lisp reader macros, we could set up any new literal syntax we like pretty easily, including whatever string-quoting scheme makes sense for the application. It also lets you completely change the rules of the language, which is great if you want to make a new language, but can cause Tower-of-Babel problems if you're not careful, both at the team level, and worse, at the ecosystem level. I'm not sure if true reader macros are a good idea for Hy, but I won't oppose it.

Clojure had a compromise solution with the tagged literals. You would usually apply a tag to strings representing individual objects (like the regex example), or a to a Hy data structure. I think we could get at least 80% of the power of reader macros using a combination of tagged literals, strings, and Hy's reader. With the help of the reader, you could put an entire toplevel form (or even the whole file) in a string, with any tweak you like to Hy's syntax. You preprocess it however you like, then if the result is valid Hy, you can pass it to Hy's reader for evaluation.

For this to work, you need a string syntax that's both short enough to use for individual atoms but robust enough to contain arbitrary Hy code. Heredocs would certainly work for the larger strings, but are too cumbersome for lists of smaller atoms. Proposal C is not great for either extreme. It's a little too long for atoms (but could work), would be awkward for a toplevel form for the same reasons as doctests and would probably require using Unicode delimiters for the whole file.

### Proposal D
A literal of this form begins with `#"`, followed by any target string terminated by either `:` or `:` and one newline, followed by the body. The body is terminated by the target string followed by a `"`, unless you opened with the newline, in which case it's terminated by a newline, the target, `"`. Examples:
```
=> #":foo"
'foo'
=> #":
docstring
"
'docstring'
=> #"/:"don't"/"
'"don\'t"'
=> #"END:
Don't say,
"I can't!".
END"
'Don\'t say,\n"I can\'t!'
=> #""":

Triple quotes?
We can still begin and end with newlines!

"""
'\nTriple quotes?\nWe can still begin and end with newlines!\n'
=> #""":3-"'s!"""
'3-"\'s!'
```

This does pretty much everything I want, with a syntax that doesn't look too heavy, and can even resemble Python's triple quotes if you want. Note that empty target strings are allowed. The leading `:` in `#":foo"` looks like a keyword, so you're already used to glossing over that. Also, the leading `:\n` option resembles the same block format from Python, so it doesn't look too weird. It can also work much like heredocs if you need it to, and you don't have to strip the leading `\n`, but can still include one if you want.

I might also like a way to strip out leading indents. Tagging these string is still a little ugly: `#re #":/"don't"/"`. If anyone has another proposal/modification that meets my requirements, I'd like to see it.

**Comment by Kodiologist** [comment]
> There's no point in supporting paired delimiters like that unless you can also nest them like Perl does. All or none.

I don't see how you came to this conclusion. In any case, nested delimiters could be added, but it seems like a lot of lexing complexity (particularly if you also allow escaped delimiters per Perl) for little benefit; it's better to just choose a delimiter you're not using in the string.

It looks like proposal D is similar to C but allows the delimiter to be multiple characters, and in exchange requires an extra character at the front and back (and also there's this stuff about newlines, but I don't think that's important because you seem to intend it solely for docstrings, so one could get the same behavior by making Hy strip docstrings when compiling `fn`, `fn*`, or `defclass`). To me it seems better to use Unicode delimiters, which are more visually compact and just as easy to type if you edit your .XCompose (or whatever the equivalent is outside Linux) appropriately.

If you're still keen on the possibility of multiple-character customizable delimiters at the expense of brevity, though, we could make `#qC` fancier to accommodate this. For example, `C` could be special-cased such that if it's `=`, then you can use as many `=` characters as you want to start the string and then the same number to end it, a la Lua's long brackets. Or if `C` is `:`, then you can write any string followed by another `:`, and that's your end string. Whatever floats your boat. I don't see myself using these, so it's no skin off my nose.

**Comment by Kodiologist** [comment]
Also, I should say that I'm against proposal D because it requires double quotes, which is a problem if you wanted this syntax to help you get Hy code into a string that's double-quoted, as in a shell, for example.

**Comment by gilch** [comment]
> I don't see how you came to this conclusion.

The special case of paired delimiters is extra complexity *by itself*. I think it's worth the extra complexity if you can nest them, but otherwise don't bother. If the opening character is always the closing character, that's simpler.

> and also there's this stuff about newlines, but I don't think that's important because you seem to intend it solely for docstrings

Actually docstrings are the one place you *don't* need it. Python's docstring tools already strip it out. I want this for the cases I'm quoting some other language, but also want its normal formatting without the opening quote screwing up the indentation. I don't want to have to strip it myself. Lua's brackets do strip one initial newline, if present. You can still start with a newline by simply adding another one. Requiring the newline at the end in that case is less important to me, but I do think it looks nicer.

> In exchange requires an extra character at the front and back

Actually, we could modify D to do it with only one extra, but the triple-quote trick needs both to look pretty.

> If you're still keen on the possibility of multiple-character customizable delimiters at the expense of brevity, though, we could make #qC fancier to accommodate this.

I like this plan. We get both the single-character brevity we want for atoms, and the long delimiters we need for other language. I'm not sure what form it should take. The `=` proposal seems reasonable, but once you get up past `===`, an arbitrary end string would be shorter. I also don't trust humans to count bigger numbers accurately, but they'd also come up a lot less often. Hmm. I think it's worth getting some more opinions.

**Comment by gilch** [comment]
On second thought, how do you quote `=` itself in a `#q=` string? What if the body starts or ends with `=`? This doesn't work. 

We need a pair of delimiters for the special case. We could use Lua's approach `#q[[`, `#q[=[`, `#q[==[`, etc. But by then why not include an arbitrary string (sans `[]`) between the `[[`? We could also point the inner delimiters the other way like `#q<target>` a la XML. The closing part could just be `target` itself instead of `<target>` or `</target>`.

**Comment by gilch** [comment]
@hylang/core the two best options for custom delimiters seem to be like `q[foo[` and `]foo]` or like`q<foo>` and `foo`. I don't have a very strong opinion, does anyone have a preference, and why?

**Comment by kirbyfan64** [comment]
IMO Lua's style fits more with the Python readability goals.
