### ISSUE TITLE
Special forms can be string literals?

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1317]
I noticed a quirk in the compiler, was this intentional?
```
=> (defmacro foo [x] `(print "foo" ~x))
import hy
from hy import HyExpression, HyString, HySymbol
hy.macros.macro('foo')((lambda x: HyExpression(((([] + [HySymbol('print')]) + [HyString('foo')]) + [x]))))
<function <lambda> at 0x00000232735AA6A8>
=> ("foo" 2)
print('foo', 2)
foo 2
=> ("+" 1 1)
(1 + 1)
2
```
It seems that special forms and macros can be named by string literals instead of symbols. This doesn't seem to work for callables though.
```
=> ("print" 2)
'print'(2)
Traceback (most recent call last):
  File "c:\users\me\documents\github\hy\hy\importer.py", line 177, in hy_eval
    return eval(ast_compile(expr, "<eval>", "eval"), namespace)
  File "<eval>", line 1, in <module>
TypeError: 'str' object is not callable
```

**Comment by Kodiologist** [comment]
Using a symbol in these positions is simply one of the syntactic conventions that the compiler doesn't enforce, like using square brackets instead of parentheses around the second argument of `for`. If you want a stricter compiler, you should probably make an umbrella issue for that. Fixing this would probably entail more declarative machinery for the compiler that would produce better error messages in situations such as #1277.

**Comment by Kodiologist** [comment]
Actually, this issue turns out to be due simply to using `HyString` in some cases where we should be using `HySymbol`.
