### ISSUE TITLE
defn should support a map for pre and post conditions

### ISSUE THREAD

**Issue by munk** [hylang/hy#1318]
It would be nice if I could put a map after the argument list for a function that was used for runtime assertions of pre and post conditions, similar to Clojure.

    (defn abs [x]
       {:pre [(int? x)]
        :post [(< 0 x)]}
       ...)

**Comment by Kodiologist** [comment]
I think that would be a pretty niche feature for a macro of such central importance. Why not write your own macro to implement this? You can see the implementation of the standard `defn` in `hy/core/bootstrap.hy`.

**Comment by munk** [comment]
@Kodiologist It's no more niche than a lisp running on python ;) 

Design by contract is a very powerful feature. I think it's one of the greatest ideas in software engineering for demonstrating correctness.

I could certainly write my own macro to do this, but for non-toy programs, I'd be using that over defn most of the time. Because of that, I'd prefer if it was native to the language.

This has precidence in [Clojure here](https://github.com/clojure/clojure/blob/clojure-1.9.0-alpha14/src/clj/clojure/core.clj#L306) and it seems like it would be straightforward to implement.

I'm happy to take a shot at implementing it if you're open to the idea.

**Comment by gilch** [comment]
There's no need to alter the compiler. A custom `defn` macro can replace the one in `core/bootstrap`. See the [defn macro](https://github.com/hylang/hy/blob/master/hy/contrib/multi.hy#L76) from `contrib/multi`. 

Domain-specific forms belong in third-party libraries, not Hy proper. General-purpose forms, on the other hand, should be in Hy core or contrib or extra, to avoid fragmentation of the ecosystem. This "design by contract" setup is generally useful. That's why Clojure has it built in. Considering that precedent, I'd be willing to put a good implementation in contrib, with our other experimental features.

Macros are not even required for this. A Python decorator could theoretically do this, but a macro might have less overhead. It would also be nice if the `defn` from `contrib/multi` were compatible.

**Comment by Kodiologist** [comment]
> Macros are not even required for this. A Python decorator could theoretically do this

It might be worth checking for existing Python libraries for this first, then.

**Comment by gilch** [comment]
My thoughts as well. I was just looking at that. But decorators have the overhead of an additional function call. It seem like it would be easy to do pre-conditions as a macro without that overhead. Postconditions might be more tricky with multiple returns, exceptions, `yield`, and `async`/`await`. We currently don't have `async`/`await` implemented, but that should change. Multiple returns are also controversial, but might happen.

**Comment by gilch** [comment]
On second thought, a decorator could check `if not __debug__` and just return the function without wrapping it when assertions are off. This would eliminate any overhead after loading the module when assertions are off. This makes a macro implementation seem less important to me. But a preconditions macro really would be easy.

**Comment by gilch** [comment]
A postcondition macro could maybe expand to a try-finally surrounding the function body. That seems like less overhead than wrapping the function. But it might be tricky for the aforementioned reasons.

**Comment by gilch** [comment]
I did some looking and found:

* https://github.com/stefankoegl/python-decontractors (BSD-3) This one looks unmaintianed, but if it's not broken, no need to fix it.
* https://andreacensi.github.io/contracts/ (LGPL) This one looks pretty nice. The weak copyleft means we can't just pilfer it, but we could recommend it.

There's also `zope.interface` package that looks too complicated, and a PyDBC that's based on a Python 2 metaclass, probably not what we want.
[PEP 316](https://www.python.org/dev/peps/pep-0316/) is also worth mention.

These aren't particularly compelling though. Basic pre and post condition decorators would be so easy that I'm tempted to roll my own.

**Comment by gilch** [comment]
Yeah, this is pretty simple as a decorator.
```Python
from functools import wraps

def contract(*, pre=lambda *a, **kw: True,  post=lambda r: True):
    def wrap(f):
        if not __debug__: return f
        @wraps(f)
        def wrapper(*args, **kwargs):
            assert pre(*args, **kwargs), f"""Precondition not met.
  args: {args}
  kwargs: {kwargs}"""
            res = f(*args, **kwargs)
            assert post(res), f"""Postcondition not met.
  returned: {res}"""
            return res
        return wrapper
    return wrap
```
Example usage (also works as a doctest).
```Python
    >>> @contract(
    ...         pre=lambda a,b: a<b and a>0,
    ...         post=lambda r: r==42)
    ... def foo(a, b):
    ...         return a+b

    >>> foo(40,2)
    Traceback (most recent call last):
      ...
    AssertionError: Precondition not met.
      args: (40, 2)
      kwargs: {}
    >>> foo(1,2)
    Traceback (most recent call last):
      ...
    AssertionError: Postcondition not met.
      returned: 3
    >>> foo(2,40)
    42
```
The lambdas are a bit awkward, but it seems perfectly usable. The traceback doesn't say exactly what expectation failed, but it points you to the right to the test definition, and prints the failing data. 

From its docs, PyContracts appears to use `eval`'d strings instead of lambdas like I did. This could give you a prettier traceback that includes the test itself, but strings seem more error-prone. It shouldn't affect performance too much, since it would only have to be compiled once, like `namedtuple`.

I do think a macro could make this better in Hy. We could use the Clojure syntax and include the test itself in the traceback, unlike my decorator. If we recommended PyContracts, the test strings would have to be written in Python, or use Python's annotations, which we don't support yet #640.

**Comment by kirbyfan64** [comment]
As cool as this idea may seem...it seems a bit like a niche use case. After all, this is Python: all of these could be replaced with basic assertions:

```hy
(defmacro check [&rest conds]
  `(do
    ~@(map (fn [cond] `(assert ~cond ~(str cond)))))
```

Then you could just run:

```hy
(defn abs [x]
  (check (int? x) (something-else x))
  (setv ret (if (< x 0) (- x) x))
  (check (>= ret 0))
  ret)
```

Admittedly, you lose a bit of functional-ness here, but this could easily be expanded on.

**Comment by gilch** [comment]
It doesn't work--`map` takes two arguments. I can guess what you're trying to do though. But the `setv ret ...`/`check (... ret ...)`/`... ret)` pattern has to be rewritten every time. Boilerplate like that belongs in the macro. So you could make a `post` macro that does that for you. That would be better.
```Hy
(defn abs [x]
  (check (int? x) (something-else x))
  (post (>= result 0)
    (if (< x 0) (- x) x)))
```
But how often do you use them separately? If you're into design by contract, you test the whole signature pretty often. And they're always right next to each other. So it's simpler to put both pre-and post in the macro:
```Hy
(defn abs [x]
  (contract
    {:pre [(int? x) (something-else x))]
     :post [(>= result 0)]}
    (if (< x 0) (- x) x)))
```
That...looks familiar.

And again, if you're into design by contract, you're doing this for every function. So that `(contract ...)` part is more boilerplate. So you make a new `defn` macro that does that for you. I still think it should be in contrib, so this only happens once.

**Comment by Kodiologist** [comment]
Three years later, I still think this kind of thing, if you want it, should be in its own macro instead of the standard `defn`.
