### ISSUE TITLE
Equality should require 2 arguments

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1332]
On hy 0.13:

```
(!= 1)
  File "<input>", line 1, column 1

  (!= 1)
  ^----^
HyTypeError: b"`!=' needs at least 2 arguments, got 1."
```

as expected but:

```
(= 1)
> True
```

This can lead to bad error messages. This message for instance was deeply nested and took some time to isolate.

```
(list (remove (= 1) (range 10)))
> TypeError: 'bool' object is not callable
```

**Comment by gilch** [comment]
Clojure:
```Clojure
user=> (= 1)
true
```
Common Lisp
```
* (= 1)

T
```
This is by design. `=` can take multiple arguments in Lisp. Say you have a list of things you want to make sure don't differ from a known value. You can simply unpack the list, and it works even if it happens to be empty. `(= known-value #* list)`. That's one more special case you don't have to check for, which is even more important when writing macros. Most Lisp operators are like this, not just `=`.

If you *need* a version restricted to two arguments for some reason, write your own function.

**Comment by gilch** [comment]
In fact, it's unusual that Hy's `!=` requires two arguments. The problem is, it's not clear what the one-argument case should be.

Common Lisp
```Lisp
* (/= 1)

T
```
But in Clojure:
```Clojure
user=> (not= 1)
false
```
That's because Clojure's version literally means
```Lisp
* (not (= 1))

NIL
```

**Comment by Kodiologist** [comment]
Yep, it seemed clear to me that `(= x)` and `(is x)` should be true whereas `(!= x)` and `(is-not x)` don't make much sense. These details of the operators aren't documented (yet), but `tests/native_tests/operators.hy` has lots of examples.
