### ISSUE TITLE
Allow ~@ splice on None

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1335]
Related #896.

In most Lisps, `nil` is also the empty list. In Hy, `nil` used to be `None`. Python does not consider `None` to be iterable, but `unquote-splice` could have a special case for it. This would make macro writing easier. It's a common Lisp idiom to splice in an `if` expression during a macroexpansion which can optionally add some things or not. In Hy you have to put an empty iterable in the else part to make this work. If `None` were allowed, you could leave that off.

While we're at it, it would also be nice for macro writing if a `HyList` instance `+` `None` just returned the instance, but this is less consistent with Python lists.

**Comment by gilch** [comment]
By the way, Hy's `cons` already considers `None` to be the empty list, so there's precedent for this kind of special casing. Compare:
```
=> (cons 1 None)
from hy.core.language import cons
cons(1, None)
(1)
=> (type (cons 1 None))
from hy.core.language import cons
type(cons(1, None))
<class 'hy.models.HyExpression'>
=> (cons 1 '())
from hy.core.language import cons
from hy import HyExpression
cons(1, HyExpression([]))
(1)
=> (type (cons 1 '()))
from hy.core.language import cons
from hy import HyExpression
type(cons(1, HyExpression([])))
<class 'hy.models.HyExpression'>
```

**Comment by woodrush** [comment]
#1349 fixes this. The current `unquote-splice` receives the value of the form inside and passes it to Python's `list`. When the form inside `~` evaluates to `None`, it produces `list(None)`, but since `None` is not iterable, it results an error. Instead of passing the form to `list`, #1349 passes the form to a function that returns `[]` when it receives `None`, allowing `None` to be spliceable.
