### ISSUE TITLE
Perplexing keyword behavior in splice

### ISSUE THREAD

**Issue by gilch** [hylang/hy#1352]
```Hy
(defn print-args [&rest args &kwargs kwargs]
  (print args kwargs))
```
```Python
=> (print-args :key 42)  ; normal keyword magic
print_args(key=42)
() {'key': 42}
=> (print-args ':key 42)  ; quote to pass keyword as data
from hy import HyKeyword
print_args(HyKeyword('\ufdd0:key'), 42)
('\ufdd0:key', 42) {}
```
That was strange for a Lisp, but easy enough to understand.

```Python
=> (eval `(print-args ~@[:key 42]))  ; raw keyword
from hy.core.language import eval
from hy import HyExpression, HySymbol
eval(HyExpression((([] + [HySymbol('print_args')]) + list(['\ufdd0:key', 42]))))
('\ufdd0:key', 42) {}
=> (eval `(print-args ~@[':key 42]))  ; quoted keyword
from hy.core.language import eval
from hy import HyExpression, HyKeyword, HySymbol
eval(HyExpression((([] + [HySymbol('print_args')]) + list([HyKeyword('\ufdd0:key'), 42]))))
() {'key': 42}
```
Somehow it became the opposite? Is this how it's supposed to work?

**Comment by Kodiologist** [comment]
I think so. The trick is that in Hy, unlike most Lisps, keywords don't evaluate to themselves. They evaluate to strings, not `HyKeyword`s. So the expression `` `(print-args ~@[:key 42])`` evaluates to `(print-args "\\ufdd0:key" 42)`; if you evaluate this, the compiler will see the string `"\\ufdd0:key"` instead of a literal keyword. By contrast, `` `(print-args ~@[':key 42])`` evaluates to `(print-args :key 42)`. If you want to pass a real `HyKeyword` to `print-args` here, you need **two** single quotes (i.e., `` `(print-args ~@['':key 42])``) because you're evaluating `:key` twice, once by `~@` and once by the `eval`.
