### ISSUE TITLE
Statements pulled out of the second argument of (assert) aren't added to the AST

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1390]
$ echo '(assert (do (f1) (f2)) (do (f3) (f4)))' |  hy2py
    f1()
    assert f2(), f4()

Given [how the Python language reference describes `assert`](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement), I guess this should compile to:

```Python
if __debug__:
    f1()
    if not f2():
        f3()
        assert not 1, f4()
```

**Comment by gilch** [comment]
This seems related to the ordering problem of #1342, (and #588, #1362). Hy still has trouble compiling statements inside statements. I'd have expected the wrong order here too, but it's strange that it gets left out completely instead.

We should probably check how Hy compiles every type of Python statement when they contain statements. In particular, what happens when sub-statements raise exceptions or have other side effects that care about ordering?

> I guess this should compile to:

That's the right track, I think. It might be easier to compile in some anon vars in a couple places. But how does this interact with Pytest? Will it still print out errors sensibly? I know that pdb will list Hy source, since Hy puts source position information in the ast. And Hy exception tracebacks print Hy source too.

```Python
        assert not 1, f4()
```
Why `not 1` instead of `False`? On Python 2, I suppose `False` (or `None`) could be shadowed by something else (a design flaw corrected in Python 3), not that anyone actually does this. But then, wouldn't `0` be simpler? Any false value will trigger a Python assert. Does it need to be the one true `False` for some reason?

If we *do* care what particular false value `assert` gets (does Pytest use this?), then it should compile like
```Python
if __debug__:
    f1()
    _hy_anon_var_1 = f2()
    if not _hy_anon_var_1:
        f3()
        assert _hy_anon_var_1, f4()
```

**Comment by gilch** [comment]
But, `f3()` could mutate the `[]` returned by `f2()`, preventing the `assert` from triggering at all, which does not seem correct. I suppose we could use it if possible, and fall back to `assert 0` if not.
```Python
if __debug__:
    f1()
    _hy_anon_var_1 = f2()
    if not _hy_anon_var_1:
        f3()
        _hy_anon_var_2 = f4()
        assert _hy_anon_var_1, _hy_anon_var_2
        assert 0, _hy_anon_var_2
```
I don't know if we even need this though.

I looked at Pytest. It's doing some AST rewriting, so it might not work right. Hy can't be expected to support this kind of thing in all cases. But it also look like Pytest doesn't rewrite things at all if there's a second expression (the message part) in the `assert` anyway, so I guess it doesn't matter here.

**Comment by Kodiologist** [comment]
>  But then, wouldn't `0` be simpler?

Yeah, that's true.
