### ISSUE TITLE
Function docstrings don't set __doc__

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1402]
Python:

```
>>> def hi(): "Hello"
>>> hi.__doc__
"Hello"
```

Hy:

```
=> (defn hi [] "Hello")
def hi():
    return 'Hello'

=> hi.__doc__
None
```

However hy classes do set the doc attribute correctly.

This came up as I was reviewing setting docstrings to use font-lock-doc-face rather than font-lock-string-face.

**Comment by Kodiologist** [comment]
I think you've been confused by Hy's implicit `return`. Notice that in

    def hi():
        return 'Hello'

`'Hello'` is not a docstring. If you want a function that has a docstring, does nothing, and returns `None`, you need to write that in Hy as `(defn hi [] "Hello" None)`.

**Comment by gilch** [comment]
Python avoids this issue by requiring an explicit return in a function def. Clojure avoids this issue by putting the docstring [*before* the arguments vector](https://clojuredocs.org/clojure.core/defn). It wouldn't be difficult to alter the `defn` macro to do it Clojure's way. I'd be fine with that, but I'm not sure if that would be a popular change, since Common Lisp appears to do it like Hy does.
```Lisp
* (defun hi () "Hello")

HI
* (documentation #'hi T)

NIL
* (defun hi () "Hello" nil)
WARNING: redefining COMMON-LISP-USER::HI in DEFUN

HI
* (documentation #'hi T)

"Hello"
```
And it's also more like Python where it is now.

Emacs Lisp also puts it after, but interestingly, it treats a single string in the function body as *both*. This may be why Hy's behavior surprised you.
```Elisp
ELISP> (defun hi () "Hello")
hi
ELISP> (hi)
"Hello"
ELISP> (documentation 'hi)
"Hello"
```

But because I'd expect the majority of Hy users to have first learned either Python or Clojure (and because Emacs Lisp is the first Lisp for many), we ought to explicitly explain in the docs for defn that the implicit return has priority over docstrings. And, in fact, the existence of docstrings isn't even mentioned there. So I'll reopen this until we've done at least that much.
