### ISSUE TITLE
feature or bug of `as->` bound variable behaves like a generator?

### ISSUE THREAD

**Issue by minghu6** [hylang/hy#1489]
for example:

```hy
(as-> 10 x (print x) (print x))
;; 10
;; None
```
x can be exhausted even by `zero?` `none?` etc.

**Comment by minghu6** [comment]
And

```hy
(as-> 10 x)
(print x)
(print x)
;; 10
;; 10
```

**Comment by gilch** [comment]
`as->` is not `let`. It's for nesting forms, just like `->` and `->>`, but lets you specify where the substitution occurs in each list. The case of `(as-> 10 x (print x) (print x))` behaves exactly as intended, like `(print (print 10))` Since `print` always returns `None`, of course the outer print outputs `None`. So far, this is the same as Clojure.

You can see how the macro accomplishes this with a local variable by using `hy2py` or `hy --spy`. Since this is an ordinary Python local, it exists for the normal Python scope for locals. That will exceed the scope of the `as->` form itself. Just like a `for` loop in Python. This is different from Clojure, and we may revisit this if the experimental `let` gets moved into core.

**Comment by gilch** [comment]
In the future, read the docs before opening issues.
