### ISSUE TITLE
Turn off syntax highlighting of hy expressions by default

### ISSUE THREAD

**Issue by vodik** [hylang/hy#1510]
The pretty printing is nice, and having the basic syntax highlighting to emphasis opening and closing brackets for `HyExpression` and `HyList` is certainly cool.

But I'm looking at embedding `hy` support in some of my Python projects and the ANSI colour codes are leaking into error messages, making them less legible. This should be opt-in feature of the REPL, not a default.

**Comment by Kodiologist** [comment]
See also #1429.

**Comment by gilch** [comment]
See also #1360. There are ways to turn this off, but if it wasn't the default, many users would never notice the feature even exists. That was my rationale for making pretty opt-out instead of opt-in. We could also perhaps add a command-line switch or environment variable to turn this off.

**Comment by vodik** [comment]
I think turning it on by default inside the REPL is great, but my concern is more so that it leaks outside the context and creates a something less readable. Hy objects will cross the Python boundry:

```python
>>> foo = hy.HyExpression([hy.HySymbol('foo')])
>>> repr(foo)
"\x1b[33m\x1b[22mHyExpression\x1b[39m\x1b[22m\x1b[33m\x1b[22m([\x1b[39m\x1b[22m\n  HySymbol('foo')\x1b[33m\x1b[22m])\x1b[39m\x1b[22m"
```
What happens if I'm logging exceptions with context and there's a Hy expression? Now there's noise I have to strip out:

Here's another example where it creates noise in pytest:

```
>       assert not hy.HyExpression([hy.HySymbol('foo')])
E       AssertionError: assert not HyExpression([\n  HySymbol('foo')])
E        +  where HyExpression([\n  HySymbol('foo')]) = <class 'hy.models.HyExpression'>([HySymbol('foo')])
E        +    where <class 'hy.models.HyExpression'> = <module 'hy' from '/home/simon/src/hy/hy/__init__.py'>.HyExpression
```
pytest correctly strips escape sequences, but the newline characters are literally printed and, imho, impede understanding.

And looking at #1360, @kirbyfan64 properly points out this: 

> Python reprs that are known to not round trip are conventionally contained in <>, for example:

But the escape sequences prevent round tripping from working.

**Comment by gilch** [comment]
> I think turning it on by default inside the REPL is great

So, how do you want this to work?

It does round-trip if you copy-paste in most terminals, since the coloring doesn't make it into the system clipboard. This is the usual use case for round-tripping. You can also strip the color codes programmatically using clint if you need to eval a string repr for some reason. But this seems rarely useful.

In your Python repr example, you're using internal Hy models directly in a python repl. If you're creating Hy modules to be consumed from Python, you won't be exporting this stuff. Even then, making it readable in the console is as simple as `>>> print(repr(foo))`.

I said before that managing this kind of thing would be easier with dynamic vars #1089. But until that's implemented we have to settle for a module-level global. We could have PRETTY off by default, but make the repl turn it on upon startup.

Hy doesn't have a debugger of its own, but is mostly compatible with pdb, so it would be nice if the Hy model reprs were pretty there too.

Repl startup activation would prevent the Python repl from getting the pretty reprs. But it might also prevent certain uses of pdb. You can turn it back on every time, of course, but this is inconvenient. Hence my environment variable suggestion.

There might also be cases where we'd want to launch a Hy repl from a Python repl. #1323. The embedded Hy repl could also turn PRETTY on, but if you quit back to python, PRETTY would still be on. Maybe you could turn it off at exit. If it doesn't crash.

**Comment by gilch** [comment]
As for the Pytest example, pytest needs special instructions to find Hy files in the first place. Whatever setup code is doing that could also turn off PRETTY. But I don't know that it improves readability that much. For a simple `'(foo)`, sure, but once it gets nested very deeply, you'd have to copy it out, paste into your editor and indent it manually to see the structure. It would be easier to leave PRETTY on, paste it into a string literal and print it at a repl.
