### ISSUE TITLE
Bodies should be optional in more places where Python accepts `pass`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1539]
I notice in particular that Hy doesn't allow `(while (f))` or `(for [x (generator)])`.

**Comment by gilch** [comment]
Python takes `pass` literally anywhere a statement is allowed. (Notably, not in the "body" of `lambda`) But in Hy everything is an expression. What value should `(while (f))` evaluate to? `None`? or the result of `(f)`? What should an empty `for` evaluate to?

Should we allow empty `try` forms too like `(try (except))` or `(try (finally))`? A `pass` is allowed there. But what should they evaluate to?

I think the rest already work with empty bodies.

**Comment by gilch** [comment]
> while and for return None in every other case.

Good point.
> the point of a try with no body.

If it's written directly in production that way, yeah, it's got to be an error. But during development, you might comment stuff out like
```Hy
(try
  ;; (risky-foo)
  (finally
    (stuff-I-still-want-running))
```
Restructuring the entire form to pull out the finally when you just want to disable one line is a pain. In Python, you'd have to add a `pass` if it was the entire body though. We actually have a `comment` macro that substitutes a `None` for this kind of thing. But the line-wise `;` or form-wise `#_` would have the same problem. You'd need to add a `None` or something.

There are certain tradeoffs between flexibility and enforcing correctness for this kind of thing, but in Lisp, because of macros, we want to avoid special cases more than we want to enforce correctness for this kind of thing. If a macro expands to a `try` form, and the body could reasonably be empty for the macro's semantics, then it's an additional special case we're forcing the macro writer to handle unnecessarily.

**Comment by Kodiologist** [comment]
Yeah, that makes sense.
