### ISSUE TITLE
Module docstrings don't work with together with Hy core imports

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1540]
Similarly to #1367, any automatic imports from core will prevent a string literal from being the first statement in a module, and hence from being the module docstring.

    $ echo '"hello world" (print (get [1 2] 0))' > test.hy
    $ hy -c '(import test) (print test.__doc__)'
    1
    hello world
    $ echo '"hello world" (print (first [1 2]))' > test.hy 
    $ hy -c '(import test) (print test.__doc__)'          
    1
    None

**Comment by gilch** [comment]
We can just set the `__doc__` global and put module docstrings wherever we please. But I'd rather get rid of autoimports altogether somehow. It's causing a lot of problems and the above is just one of them. Hy's core is not discoverable with `dir`. We can't easily `import *` from a Hy module, since the Hy core we happen to use in that module comes with it.

What we really want is our own `builtins` module for Hy. But Python doesn't have an easy way to add that. And dumping our "builtin" stuff into Python's `builtins` is not nice to the Python side. So we autoimport. #1407 had some ideas on how to deal with that differently.

**Comment by vodik** [comment]
> What we really want is our own builtins module for Hy. But Python doesn't have an easy way to add that.

It does... we just have to drop Python 2 :wink: See [BuiltinImporter](https://docs.python.org/3/library/importlib.html#importlib.machinery.BuiltinImporter)

**Comment by gilch** [comment]
Wait, what? Does this really do what we need? Python 2.7 also [has a "BuiltinImporter" class](https://docs.python.org/2/library/imputil.html#imputil.BuiltinImporter), I checked. But it's not clear to me how to use it or what it's good for from those linked docs.
