### ISSUE TITLE
Two very important questions

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1592]
1. Why is it called Hy?
2. Why is our mascot a squid?

@paultag

**Comment by kirbyfan64** [comment]
2. Because the cuttlefish is adorable.

**Comment by zackmdavis** [comment]
One also wonders whether it's not a coincidence that the name can be [stylized with _λ_ s](https://github.com/hylang/hy/blob/eec4a178b84301c396022233baa1e08a7b288918/docs/_static/hy-logo.svg).

**Comment by paultag** [comment]
> 1. Hy is a refference to Hymenoptera. Paultag wrote a master thesis about swarm intelligence if i recall correctly.

Not masters, just did some research back in the day. I was dusting some of that off, and I wanted to use Lisp, but I needed some libraries in Python I didn't want to use. This would up resulting in the earliest version of Hy, which was deeply bad and very crude -- but it worked!

Hymenoptera are an order of insects that exhibit swarm behavior that I was modeling at the time -- decentralized. There's no top-down command and control within an Ant colony or with wasps. That eventually became 'Hy' because 'Hymenoptera' is long and spelling it without using spellcheck sucks. Plus it's kinda like "Py".

> 2. I don't recall how we wound up with the cuttlefish.

@cwebber saw that we didn't have a logo, and drew one in ASCII. It was adorable and he called it Cuddles. We used that for a few months, but then @aldeka was nice enough to see it, know that it wasn't anywhere near as good as it should be, and came up with the current version of Cuddles!

**Comment by cwebber** [comment]
> @cwebber saw that we didn't have a logo, and drew one in ASCII. It's also a Cuttlefish, not a squid :). It was adorable and he called it Cuddles. We used that for a few months, but then @aldeka was nice enough to see it, know that it wasn't anywhere near as good as it should be, and came up with the current version of Cuddles!

Accurate... though, pronouns have been updated since :)

**Comment by Kodiologist** [comment]
Congratulations on coming out, then, and thanks for the mascot.

**Comment by cwebber** [comment]
BTW, here was the original ascii art mascot:

```
             ______
      _.----'#'  # '
    ,'  #'    ,#  '
   ('   (w)  _,-' |
  // // /'.____.'
  \|\||/
   LET'S CUDDLEFISH
```

**Comment by cwebber** [comment]
I also made the original logo btw.  I think I used a lamda from some set of defaultt (La)TeX fonts and flipped it around into the "h" and "y" IIRC.
