### ISSUE TITLE
Python allows uppercase string prefixes (e.g., R"raw string") but Hy doesn't

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1620]
Bug or feature?

**Comment by kirbyfan64** [comment]
Given that we're already restricting the case of NaN and such, IMO they shouldn't be case insensitive. This fact actually comes up every time someone proposes an additional prefix, since the number of permutations is so high.

**TL;DR:** If the decision for Python were made today, they probably wouldn't be insensitive.

**Comment by Kodiologist** [comment]
> TL;DR: If the decision for Python were made today, they probably wouldn't be insensitive.

Yeah, that's what I'd think. It seems like a clear design mistake. The question then becomes whether we want to fix or retain this peculiarity of Python.

**Comment by vodik** [comment]
Vote for case sensitivity.

We already deviate enough from Python here that it doesn't make sense to match: Triple quotes don't work, multi line strings are done differently (`#[FOO[ ... ]FOO]`), etc.

**Comment by gilch** [comment]
I also find @kirbyfan64's reasoning persuasive. Let's keep enforcing the lower-case string prefixes then. @vodik yes, Hy strings already deviate quite a bit from Python's. We can always use `ast.literal_eval` if we need to read in a Python string literal in Hy. Well, except for f-strings, but those aren't really literals.

Since enough of us agree on the status quo, I think we can close this.

**Comment by gilch** [comment]
Although more docs wouldn't hurt.

**Comment by Kodiologist** [comment]
Should we reopen with [docmebro]?

**Comment by Kodiologist** [comment]
Don't mind if I do.
