### ISSUE TITLE
New mangling rules interfere with pytest test collection

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy#1634]
For example,

```
(defun test-foo->bar [])  ; 'hyx_test_foo_XgreaterHthan_signXbar'
```

The new `hyx_` prefix being the issue of course.

**Comment by Kodiologist** [comment]
See #1634.

**Comment by pyx** [comment]
The way used in #1625 to circumvent this is teaching py.test what to look for in `setup.cfg`:
```ini
[tool:pytest]
python_functions=test_* is_test_* hyx_test_* hyx_is_test_*
```

In addition to `hyx_` prefix, something like `(defn test-maybe? [])` will cause problem (also addressed in above), too.  The `is_` prefix is way more harder to avoid, since that's by-design.  So, users are on their own. I believe a section dedicated to testing in documentation is the way to go. It should show:

1. as a warning, that this problem exists, users should either avoid special characters in test functions, or do what mentioned above in `setup.cfg`
2. ways to setup auto test discovery for unit testing frameworks (py.test, node2, etc.) , for example, py.test by default, does not check inside `.hy` files, to find hy source code, put this in `conftest.py`
  ```python
  from pytest import Module

  def pytest_collect_file(path, parent):
      if path.ext == ".hy" and path.basename.startswith('test_'):
          return Module(path, parent)
  ```

**Comment by gilch** [comment]
Could we make the `hyx` a suffix instead? Do we even need it at all at this point? It's just a signal to `unmangle` right? Couldn't we use a condition like "has an even number of X" as the condition instead? (not zero). This would minimize interference with that kind of name-reading tool.

We could also always treat `X` as punctuation that must be escaped--mangle any `X` to `Xlatin_capital_letter_xX` to maintain full reversibility. (Or just `XX` #1577).

**Comment by Kodiologist** [comment]
Using pytest on Hy code isn't something we officially support or document at all, right now; the existing support is only for Hy's internal use. But see #1529.
