### ISSUE TITLE
Argument-less Tags

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1642]
While making some changes for [this PR](https://github.com/algernon/adderall/pull/8), I noticed that tag macros can't be used without arguments.  Is that a necessary property of tag macros?

**Comment by Kodiologist** [comment]
The way tag macro calls are parsed is that a `HASHOTHER` token is combined with the following token into the model `(dispatch-tag-macro "tagname" expr)`. If you could call a tag macro without an argument, then presumably that would parse as `HASHOTHER` alone, which would product `(dispatch-tag-macro "tagname")`. But if a tag macro could be called with one argument or none, how is the parser supposed to tell which you mean? It can't just check the parameter list of the tag macro because that's not known until compile-time.

**Comment by brandonwillard** [comment]
That sounds very much along the same lines as my initial hunch.  Thanks for providing the details!
