### ISSUE TITLE
`hy.core.language` import in `hy/__init__.py

### ISSUE THREAD

**Issue by brandonwillard** [hylang/hy#1697]
While working on Hy I've run into problems involving the `hy.core.language` imports in `hy/__init__.py` on numerous occasions.  These imports are automatic and necessarily trigger Hy compilation&mdash;among other things&mdash;when loading literally anything from the package.  

If one intends to simply import the model objects from `hy.models`&mdash;for example&mdash;then `hy/core/language.hy` is compiled, which seems like a lot of unnecessary work.  Furthermore, this behavior obfuscates the true source of errors&mdash;where there are any&mdash;by triggering package-loading exceptions for functionally independent parts of the package.

It seems like we could replace the `hy.core.language` imports with their Python equivalents, or simply remove those from `__init__.py` altogether.
Is there something to this scenario that would warrant retention of `hy.core.language` within `hy/__init__.py`?

**Comment by Kodiologist** [comment]
I like the way you're thinking. I've been bitten by this before. It ought to be possible to access pure-Python parts of the hy namespace without invoking the compiler.

There are currently four imports from `hy.core.language` in `__init__.py`:

- `mangle`
- `unmangle`
- `read_str`
- `read`

The first two can just be imported from where they're actually defined, `hy.lex`, instead of `hy.core.language`. The latter two could be written in Python instead of Hy.

**Comment by brandonwillard** [comment]
Exactly!

**Comment by brandonwillard** [comment]
Maybe put these changes together with https://github.com/hylang/hy/issues/1695 in a reorganizing PR?

**Comment by Kodiologist** [comment]
That's a decent idea. I usually run the tests with `--ignore tests/test_bin.py` anyway because they're so much slower than everything else.

**Comment by Kodiologist** [comment]
> In other words, would we like to have a lightweight compiler that exclusively translates Hy AST to Python AST and implicitly relies on the current state of its target module for macro and function dependencies? 

Maybe. I see your argument, but it's hard to guess how things would shake out in practice.
