### ISSUE TITLE
`every?` should lose the question mark, or `some` should gain a question mark

### ISSUE THREAD

**Issue by Wagk** [hylang/hy#1737]
Unless this is a deliberate decision based on some factor I'm not aware of.

Personally, I'm in favor of `every?` losing the question mark.

**Comment by Kodiologist** [comment]
I'd agree that the question mark is not necessary.

**Comment by chuckwondo** [comment]
I disagree, although it is confusing. The reason `every?` ends with a question mark is because that is the naming pattern for predicates in hy, and `every?` is indeed a predicate. However, `some` is _not_ a predicate, which perhaps leads to confusion.

The `some` function returns the first "truthy" value (not necessarily `True`) returned by the specified predicate for an element of the specified collection, or `None` (not `False`) if there is no such value. If it were to instead return `True` if the specified predicate returned a "truthy" value, or `False` otherwise, then it would make sense to name it `some?`. However, `some?` may be implemented by using `some`:

```
(defn some? [pred coll]
  (not (none? (some pred coll))))
```

I can't imagine why `some` was implemented as it is, but that's why it's not named `some?`.

**Comment by Kodiologist** [comment]
I see; I wasn't aware that returning a truthy value, as opposed to a real `bool`, was considered to disqualify a function as a predicate. When possible, I think it's better for a testing function to return a meaningful value than to return a `bool` , because doing so allows for cute tricks like `(setv output (or saved-result (computation)))`. So `every?`, or rather `every`, should probably return the last true or the first false output of the predicate argument, anyway. In other words, `every` should be `(reduce and (map pred coll) True)` instead of `(all (map pred coll))`.

**Comment by Kodiologist** [comment]
`every?` is gone as of #2095.
