### ISSUE TITLE
Hy sys.executable may confuses python library

### ISSUE THREAD

**Issue by TristanCacqueray** [hylang/hy#1753]
For example this library: https://github.com/glumpy/glumpy/blob/master/glumpy/ext/glfw.py#L139
uses "sys.executable -c" with python code, which is not working with hy and results in a import error.

Perhaps the -c argument could check the command's dialect and fallback to hy.sys_executable if it's not hylang? Alternatively doing `(setv sys.executable hy.sys_executable)` fixes this issue.

**Comment by Kodiologist** [comment]
> Perhaps the `-c` argument could check the command's dialect and fallback to `hy.sys_executable` if it's not hylang?

That seems error-prone. I think we have to decide whether `sys.executable` will be Hy or Python and stick with it. Past experience (#329, #459) seems to indicate that setting it to Hy is helpful. On the other hand, the linked example in Glumpy doesn't make any sense to me. Why not just run that code directly as part of the function instead of farming it out to a subprocess?
