### ISSUE TITLE
A plug-in for PyCharm

### ISSUE THREAD

**Issue by piofel** [hylang/hy#1785]
Hy!

It may sound silly, and it is possibly not related to the list of Hy implementation issues, but for me the major obstacle for using Hy professionally is the lack of a PyCharm plug-in for Hy. Is any plan to make a one? I know there is a plug-in for Vim, but Vim does not the whole excellent job for large Python project handling as PyCharm does.

Thank you for your excellent work, kind regards!

**Comment by asemic-horizon** [comment]
This isn't what you asked, but VS Code has a Hy mode and irrelevant-to-Python, Lisp-oriented extensions such as paredit-like modes and rainbow-colored parentheses without which coding in Hy should be really painful. There's also "emoji extensions" to come up with new and colorful `deftag` macro names. 

As for the wider context (and trying to measure my words the best to avoid an editor war), I have never worked in Python-only shops, so PyCharm is a no-go professionally speaking. I've only seen it used in graduate school with people in "data science" tracks. I would prioritize any lateral effort in improving tooling on standard programming editors such as Emacs, Sublime, Atom, VSCode, etc.

**Comment by tensorfoo** [comment]
This would be a game changer. Pycharms seems to be the most popular IDE and it has excellent support for python projects (eg importing and using libraries, setting up a virtual environment, etc). The only thing lacking about Pycharms is the REPL is difficult to use. A Lispy REPL would solve a lot of problems because you can write longer functions in the REPL (it's a pain to use whitespace as syntax) as well as being able to test them out before moving them into the editor. The thing I miss the most about lisp programming is the REPL oriented development style. Hy can fill that niche nicely because it addresses the reasons why REPL use is so painful in Python.

**Comment by asemic-horizon** [comment]
This seems like something that should be posted in the Pycharm issue tracker. Even then, it's kind of like walking to a stone-stove pizza joint and asking for a microwave oven; and a Coke.

In my corner of the world Pycharm seems to be used by data scientists transitioning away from Jupyter notebooks; they soon graduate to VSCode when they start writing APIs and small test front-ends with jquery/bootstrap, and heavily using gitflow... Everyone's got their own bubble, of course.

Maybe there should be some place away from the Hylang issue tracker where editor improvements (I'm working in color schemes that enhance the effect of rainbow brackets) can be posted and discussed. But the issue tracker is probably also not the place to discuss the meta of community forums.

**Comment by tensorfoo** [comment]
It's got less to do with Python and more to do with lisp imho. There is a reason why most lisp programming in done in environments like SLIME, CIDER, LispWorks etc. It's the support for the language in the toolchain which makes programming with Lisp more productive. If you have to write lisp in a basic editor with no notion of a superior lisp, then there really isn't much of a benefit over writing straight up Python. It might even be worse because you're missing out on the tooling support for straight Python. IMHO. Macros are nice but I use them maybe 1% of the time and for most daily programming can go without them. I can see others have managed to write plugins for eg Clojure for IntellJ so if a basic plugin can be made for Hy, it would be very useful. Even Emacs and SLIME would be nice.

**Comment by piofel** [comment]
> This seems like something that should be posted in the Pycharm issue tracker. Even then, it's kind of like walking to a stone-stove pizza joint and asking for a microwave oven; and a Coke.
> 
> In my corner of the world Pycharm seems to be used by data scientists transitioning away from Jupyter notebooks; they soon graduate to VSCode when they start writing APIs and small test front-ends with jquery/bootstrap, and heavily using gitflow... Everyone's got their own bubble, of course.
> 
> Maybe there should be some place away from the Hylang issue tracker where editor improvements (I'm working in color schemes that enhance the effect of rainbow brackets) can be posted and discussed. But the issue tracker is probably also not the place to discuss the meta of community forums.

Last time when I tried to use VSCode on Ubuntu, I get some bug and uninstalled it as quickly as possible. Not everyone loves Microsoft software.

**Comment by darwin** [comment]
Just FYI. I'm trying to use IntelliJ + Cursive IDE to write some Hy. I'm almost threre, just need some help from Cursive devs to make it even better:
https://github.com/cursive-ide/cursive/issues/2329

btw. I'm using full Idea with Java+Clojure support and installed official Python plugin into it. It seems to work pretty well for editing all py files AFAICT. One just needs to properly configure Python SDK and paths to modules.

**Comment by brandonwillard** [comment]
This is not a feature relevant to the Hy core language (i.e. this repository).  Discussions like these are better suited for the [mailing list, IRC, etc](https://docs.hylang.org/en/stable/hacking.html#contributor-guidelines).
