### ISSUE TITLE
Hissp

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#1805]
@gilch, I just noticed that you started a new Lisp-on-Python project, [Hissp](https://github.com/gilch/hissp), back in May. Assuming you intend Hissp as a complete Hy alternative, rather than using it as a testbed for Hy development, are you still interested in being on Hy's core team? @brandonwillard, the same question goes for you, since you also seem to be involved.

In any case, we should link to Hissp in Hy's documentation.

**Comment by Kodiologist** [comment]
Come to think of it, this also explains why Matthew has stopped answering questions on Stack Overflow on the [hy] tag. I should probably pick that up.

**Comment by brandonwillard** [comment]
I don't understand the nature of the question; are you prompting us to quit the Hy core team because we're researching alternative approaches to Lisp/Python interaction?  Are you implying that Hy members can't&mdash;or shouldn't be&mdash;involved in anything else related to Lisp/Python interaction?  Is this a question of loyalty?  If this is motivated by a general desire to clean up core members who haven't been active in the last few months, then why don't you open an issue addressing that (and everyone else)?

If this is primarily a question of time or dedication&mdash;which you seem to allude to [here](https://github.com/hylang/hy/issues/1805#issuecomment-517927560)&mdash;then why is this issue so specifically about Hissp and not the other projects I've been openly working on *significantly more* than Hissp and/or Hy: for instance, [`symbolic-pymc`](https://github.com/pymc-devs/symbolic-pymc)?

As a matter of fact, my interest in Hissp is largely motivated by elements of [`symbolic-pymc`](https://github.com/pymc-devs/symbolic-pymc), since Hissp can serve as a lightweight, easily extensible replacement/platform for [some very specific functionality in `symbolic-pymc`](https://github.com/pymc-devs/symbolic-pymc/issues/2) and perhaps even within [`kanren`](https://github.com/logpy/logpy/blob/master/kanren/util.py#L72).

Hissp is being designed to fill more modular roles, especially the kind for which a dependency on&mdash;or a full rewrite in&mdash;Hy is difficult to justify.  The projects mentioned above are a good example; only small parts of the Hy compiler and syntax model would be useful and the rest would go unused and add unnecessary overhead.


Regardless, if I want to stop being involved with Hy, I'll tell you; you don't have to make assumptions about my interests.  Otherwise, if you want to ask what I'm up to, or request my input on Hy matters, please do *that* instead.

**Comment by paultag** [comment]
Yeah, I'm not inclined to take any action. Hissp looks neat! 

I'm heavily involved in other things at the moment, but I try to help when I can find time. I'm contributing far less than @gilch and @brandonwillard 

We've always been super open to having new core members, and I don't think we need to remove them for spending time on other projects too. Seems like a great way to keep things interesting.

I'm going to close this issue for now. If either of you want to drop out of core, open an issue. I'm inclined to push this back to trusting our teammates here.

Y'all are the best. Thanks for everything you do on Hy!

**Comment by Kodiologist** [comment]
> I don't understand the nature of the question; are you prompting us to quit the Hy core team because we're researching alternative approaches to Lisp/Python interaction? Are you implying that Hy members can't—or shouldn't be—involved in anything else related to Lisp/Python interaction?

No, I'm asking whether you guys are quitting Hy in favor of Hissp, because that's the impression I got. Well, mostly from Matthew. (Especially because he had previously mentioned wanting to open a "hostile fork" because he was angry about my indentation.) Your involvement seems relatively peripheral.

**Comment by paultag** [comment]
@Kodiologist I know this is all coming from a good place where you want the best for the project - this all seems normal. A lot of us in Debian either came from or went to Ubuntu at one point or another. I look forward to making sure we both benefit from the other -- either as a test-bed or as a way to experiment with ideas.

Let's try and keep this cool. If both want to stay core members, I don't see any reason to remove them. If they want to leave, they're (of course!) welcome to spend their time how they like.

@gilch @brandonwillard if either if you have an intention of leaving core, that's totally cool, no hard feelings, just open a ticket!

@Kodiologist I know there's some personal conflict here that I've missed, and I'm sorry to see that, but let's try to assume best intentions here. I know they both want whats best for the project too. We're all on the same time here! We're choosing to spend our time together -- it's always hard to see people who 99% agree with each-other wind up having bigger differences than people who 1% agree. 

:heart:

**Comment by Kodiologist** [comment]
> If both want to stay core members, I don't see any reason to remove them.

Yeah, to be sure. There should be no non-consensual ejection of people. (Obviously, short of somebody doing the kind of really disruptive stuff that, to my knowledge, hasn't happened in the Hyve.)

What you say is fair. Sorry if I came across as assuming bad faith. Even if folks do want to leave Hy for a fork (or rather, spiritual fork, since I don't think Hissp uses any of our code), it's not as if that's morally unacceptable or something.

**Comment by paultag** [comment]
Its alright! Let's just keep the community welcoming and productive even though disagreements. I appreciate you all, @Kodiologist, @gilch, @brandonwillard!
