### ISSUE TITLE
HyExpression . append

### ISSUE THREAD

**Issue by niitsuma** [hylang/hy#1869]
Why HyExpression does not . append?
list has.
This cause problems in   hydiomatic,   and   adderall

```hy
(setv l [1 [2] 3])
(.append l 3) ;;work
(setv e '(a 1 [2] 3))
(.append e 3) 
=> AttributeError: 'HyExpression' object has no attribute 'append'

(import [adderall.dsl [*]])
=> AttributeError: 'HyExpression' object has no attribute 'append'

(import [hydiomatic.core [*]])
=> AttributeError: 'HyExpression' object has no attribute 'append'
```

**Comment by brandonwillard** [comment]
I believe this change was made in https://github.com/hylang/hy/pull/1804.  That PR links to the relevant conversations and reasons why the change was made.

Otherwise, feel free to put in an issue/PR regarding updates to `adderall` and `hydiomatic`.  
I've been working on some directly related Python projects [here](https://github.com/pythological) and haven't had the time to update `adderall` and `hydiomatic`, so updates might not come soon.

Fortunately, those other miniKanren-based projects are written in Python, so they can be used in Hy!
