### ISSUE TITLE
Functions are always shadowed by macros when names clash

### ISSUE THREAD

**Issue by peaceamongworlds** [hylang/hy#1942]
```hy
$ > hy
hy 0.19.0 using CPython(default) 3.9.1 on Linux
=> (defmacro foo [] "macro")
<function foo at 0x7f0ec7165550>
=> (foo)
'macro'
=> (defn foo [] "function")
=> (foo) ; expect this to return "function"
'macro' ; however, clearly the macro gets called instead
=> (del (get --macros-- 'foo))
=> (foo)
'function'
```

Surely redefining a macro as a function means that the macro should get deleted? It seems like this has the potential to cause a lot of subtle bugs.

**Comment by Kodiologist** [comment]
Macros are expanded earlier than functions are called, at compile-time rather than run-time. For example, consider the program

```
(import random)

(defmacro foo [] "macro")

(when (random.choice [True False])
  (defn foo [] "function"))

(print (foo))
```

Hy needs to decide whether to expand `(foo)` into a macro before the `when` form executes and determines whether a function named `foo` even exists. So there's no way to give precedence to the function.

**Comment by peaceamongworlds** [comment]
Is this because the entire script is first compiled to Python and then run, instead of compiling and running one form at a time?

I guess in the former case there is nothing that you can do about it, but in the latter case you could look up if a macro with the same name exists and delete it if it does.

**Comment by Kodiologist** [comment]
> Is this because the entire script is first compiled to Python and then run

Yes, exactly.
