### ISSUE TITLE
`with` forms cannot parse multiple non-named with-exprs

### ISSUE THREAD

**Issue by scauligi** [hylang/hy#1993]
Currently, `with` parses like so (simplification mine):
```
=> (with [a b c d e] ...)
with b as a:
  with d as c:
    with e:
      ...
```

As a result, there is no way of writing multiple non-named forms, nor is there any way to have a non-named form anywhere other than the end.

I propose the following instead, with a set of outer brackets for the with-exprs and inner brackets for any named with-exprs:

```
=> (with [[a b] c d [e f]] ...)
with b as a, c, d, f as e:
  ...
```

**Comment by peaceamongworlds** [comment]
I guess that we should also get rid of `with*` since Python's `with` can now accept multiple clauses.

**Comment by Kodiologist** [comment]
All that sounds sensible to me. I'm a bit embarrassed I never noticed that deficiency in `with`, but I guess I never use more than one context manager at a time, anyway.

**Comment by peaceamongworlds** [comment]
Given that most of the time you only want to use a single context expression, it seems quite verbose to force users to add another pair of brackets in the most common case.

Would it not make sense to just write `_` when you do want lots of non-named forms?
```hy
(with [_ expr1 _ expr2] ...)
```

**Comment by Kodiologist** [comment]
I admit that I don't like having to use double brackets in one of the most common cases, either. I think that was required in an earlier version of Hy, in fact. Using `_` as a placeholder variable name is dangerous in Hy because it can shadow the shadow subtraction operator; even if this was a special case in which `_` was recognized by the compiler and no binding variable was actually emitted, we don't want to encourage the habit. Any other ideas for the syntax?

**Comment by peaceamongworlds** [comment]
> Using `_` as a placeholder variable name is dangerous in Hy because it can shadow the shadow subtraction operator;

This seems pretty bad. I didn't realise that this could actually happen. I came up with a small example:

``` hy
=> (with [_ (open "file.txt")] (reduce - [1 2 3]))
TypeError: '_io.TextIOWrapper' object is not callable
```

This seems like a bigger issue to me given how prevalent using `_` is in Python and many other languages. Would it not make sense to have the compiler treat `_` as special everywhere? Make it so that `_` is always compiled to `_` and `-` to `-`.

> Any other ideas for the syntax?

If we can't use and underscore, the only thing I can suggest is using some other variable name that you wouldn't care about.

**Comment by Kodiologist** [comment]
This is probably too goofy, but I thought of allowing a literal `0` in the place of a variable, which would be interpreted by the compiler as a request to not bind the context manager. That is, `(with [a b  0 c  d e] …)` would be compiled to `with b as a, c, e as d: …`.

**Comment by allison-casey** [comment]
This is similar to what I was going to propose. the only difference being form 2 would only allow one ctx manager and its binding:
```clojure
(with [single-form] body)
(with [sym bound-form] body)
(with [[explicitly grouped] [forms]] body)
```

**Comment by peaceamongworlds** [comment]
> ```hy
> (with [single-form] body)
> (with [even number of forms] body)
> (with [[explicitly grouped] [forms]] body)
> ```
This seems pretty reasonable.

**Comment by Kodiologist** [comment]
With #2011, I think our best option will probably be what I described above, but with `_` instead of `0`. If the list has only one item, it's special-cased to be understood as an unassigned context manager. Thus, no double brackets are ever required.

**Comment by peaceamongworlds** [comment]
> With #2011, I think our best option will probably be what I described above, but with `_` instead of `0`. If the list has only one item, it's special-cased to be understood as an unassigned context manager. Thus, no double brackets are ever required.

Assuming that #2011 gets merged, I think that this is definitely the best option.
