### ISSUE TITLE
The manual is missing module names

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2068]
It looks like the big doc reorganization ended up omitting the actual module names of the various contrib and extra modules; for example, the section named "Walk" documents the functions and macros in `hy.contrib.walk`, but doesn't mention the name `hy.contrib.walk` or otherwise indicate how to bring the enumerated names into scope.

Pointed out in https://github.com/hylang/hy/issues/2065#issuecomment-842377526.

**Comment by allison-casey** [comment]
good catch! I'll open a pr to fix it

**Comment by Kodiologist** [comment]
@allison-casey I think there may be a related bug in the Hy domain for Sphinx: `autofunction` and friends don't include the module name in the generated documentation, so `hy:autofunction:: hy.eval` names the function `eval`, instead of `hy.eval` as Sphinx does for Python.

**Comment by allison-casey** [comment]
yeah that's a byproduct of having `add_module_names = True` in `conf.py`. I set it to do that since we had a lot more auto imported stuff, but i was gonna remove it and just add notes to the beginning of the `core` api section and the beginning of the `extra/contrib` section in the pr to close this one. Unfortunately there's no way to do this per method its all or nothing

**Comment by Kodiologist** [comment]
Changing it should be fine now that we're getting rid of various auto-imports.
