### ISSUE TITLE
Better error names

### ISSUE THREAD

**Issue by younata** [hylang/hy#212]
We should have better names for the various syntax errors a user might commit.

For example, doing (if (statement) ((print "hello"))) should let the user know they forgot "do", instead of just raising a "ValueError: field function is required before Call"

**Comment by algernon** [comment]
This returns a better error now:

```
=> (if true ((print "hello")))
hello
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: 'NoneType' object is not callable
```

I believe this is reasonably understandable: it tells me that None can't be executed, so I'll try to find where I'm trying to call a None object, and voila, I find the `((`! We can't really suggest using `do` here, because `((some-fn-that-returns-an-fn))` is entirely valid.

Closing, because current master has an acceptable error message in this case at least.
