### ISSUE TITLE
Generated Python code missing parentheses in dictionary unpacking

### ISSUE THREAD

**Issue by martibi** [hylang/hy#2156]
When doing a conditional dictionary unpacking, hy executes the code correctly:

```hy
=> {#**{} #**{"foobar" 1} #** (if True {"other" 4} {"other" 5})}
{"foobar" 1  "other" 4}

```

However, when compiling it to Python code, the generated code is wrong:

```hy
=> (disassemble '{#**{} #**{"foobar" 1} #** (if True {"other" 4} {"other" 5})} True)
"{**{}, **{'foobar': 1}, **{'other': 4} if True else {'other': 5}}\n"
```

```python
>>>> {**{}, **{'foobar': 1}, **{'other': 4} if True else {'other': 5}}
  File "<stdin>", line 1
    {**{}, **{'foobar': 1}, **{'other': 4} if True else {'other': 5}}
                                           ^
SyntaxError: invalid syntax (expected '}')
```

The correct Python code should be:
```python
>>>> {**{}, **{'foobar': 1}, **({'other': 4} if True else {'other': 5})}
{'foobar': 1, 'other': 4}
```

**Comment by Kodiologist** [comment]
I can't replicate this on Hy master. Are you on master? Also, what's your version of Python? I suspect this is an astor bug, and on sufficiently new versions of Python, Hy doesn't use astor.

**Comment by martibi** [comment]
Thanks for the reply, I am hy 1.0a3. I just tested, it works fine on Cython 3.9.1 but the issue only occurred on Pypy 3.7.10.

**Comment by martibi** [comment]
I see from the code that astor is only used for below Python 3.9. Just a note for future references.

**Comment by Kodiologist** [comment]
Yep, I can replicate it on PyPy 3.7.10 with Hy master. It's probably an astor bug. I'm reopening this because it affects us, although I'll probably need to file an issue with astor, too.

**Comment by Kodiologist** [comment]
The fix was merged months ago, but there's still no word on whether a release is coming, and PyPI won't let you make a released package depend on a GitHub commit. This and any other bugs that we inherit from astor are thus effectively unfixable. The good news is that astor isn't needed for Python 3.9 and above, so once Python 3.8 is no longer supported (the Python developer's guide is saying October 2024 at the moment), these bugs will just become non-issues.
