### ISSUE TITLE
Monkey-patching `py.path.local.pyimport` should no longer be necessary

### ISSUE THREAD

**Issue by yuluc123** [hylang/hy#2181]
Hi
I noticed **py** is used in conftest.py but not declared in any configuration files .
In addition, py as a Python library is deprecated as its [documentation](https://pypi.org/project/py/) "py.path: uniform local and svn path objects -> please use pathlib/pathlib2 instead"

Maybe it is necessary to migrate to new dependency-pathlib2 and add it to configuration files.

**Comment by Kodiologist** [comment]
The reason we're importing `py` in `conftest.py` is just to monkey-patch `py.path.local.pyimport` in order to work around a bug that affected `pytest` (see `conftest.py`), which uses `py.path`. However, a little testing suggests that the monkey-patch is no longer necessary for the test suite to work, so we can probably drop this.

**Comment by yuluc123** [comment]
Thanks for your reply.
It seems that it should be solved. If py.path is no longer used, it should be removed from code.
