### ISSUE TITLE
Invalid string escape sequences become literal backslashes

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2254]
Python's traditional behavior given something like `"a\p"` is to silently treat it as `"a\\p"` (or equivalently, `r"a\p"`), because there is no escape sequence `\p`. Recent Pythons will produce a `DeprecationWarning` for this, although you may have to opt in to the warning. Hy currently treats  `"a\p"` as `"a\\p"` with no warning and no error.

Since we're still not at 1.0, I think we might as well jump headfirst into the future and treat invalid escape sequences as syntax errors, regardless of the underlying Python version. The literal-backslash fallback isn't useful and is liable to get the programmer into trouble.

**Comment by allison-casey** [comment]
Oh neat! I guess this brings up the question of how we want to handle versiones incremental Python changes going forward. Do we match their cadence? I.e. make it a deprecation warning on those Python versions and a syntax error on the others?

**Comment by Kodiologist** [comment]
I don't know. I guess we don't have to think about it too hard till after we're at 1.0, and it's hard to foresee new Python changes that would suggest a corresponding Hy deprecation as in this case. In the past, Hy has smoothed over some of the differences between Python versions when it's easy to do so, and I think that can be helpful.

**Comment by allison-casey** [comment]
True enough. We are getting pretty close though and this has me thinking about how we telegraph breaking changes in future builds since we can't be breaking stuff willy nilly past 1.0 anymore. We can have that process discussion when we get there though. Also, this has me realizing that hy doesn't have an option to enable deprecation warnings at all. You'd usually pass `-Wd` to python, but hy has no corresponding arg to pass that through 🤷‍♀️
