### ISSUE TITLE
Add a way to use currently defined reader macros with `hy.read-many` and `hy.read`

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2292]
Currently there is no (official) way to read code that uses reader macros defined by the active reader.

**Comment by scauligi** [comment]
This currently works:
```hy
(defreader foo 3)
(setv reader (hy.reader.HyReader))

;; import all readers from current module into reader
(hy.eval (hy.read f"(require {__name__} :readers *)" :reader reader))

(hy.read "#foo" :reader reader)
```

A slightly more direct solution is:
```hy
(hy.macros.enable-readers None reader "ALL")
```
since that's the only part of `require` we actually need.

Is `enable-readers` considered part of the public API?

**Comment by Kodiologist** [comment]
I'd say it isn't, currently. Originally Allie had intended it to be, the idea being that reader macros can be surprising, and so by calling `enable-readers` explicitly the user would be opting into reader macros. I argued that `(defreader …)` or `(require foo [:readers …] …)` was enough of an opt-in. So in her final version of the PR, `enable-readers` no longer had to be called by the user, but it remained part of the implementation.

**Comment by scauligi** [comment]
I can make a PR to clean up and expose `enable-readers` for this use-case; the only caveat is that since (like many of the functions from `hy/macros.py`) it uses `inspect.stack()[1]` to get the module of the immediate caller, which can lead to potential confusion on the off chance a user is wrapping/calling this indirectly from a utility submodule or something. I don't have a solution to that aside from making sure it's documented, so hopefully that will suffice.

**Comment by Kodiologist** [comment]
Maybe `hy.read` could have a special parameter that would enable loading all reader macros from the current module first. Or it could be a parameter of the `HyReader` constructor.

> …it uses `inspect.stack()[1]` to get the module of the immediate caller, which can lead to potential confusion on the off chance a user is wrapping/calling this indirectly from a utility submodule or something. I don't have a solution to that aside from making sure it's documented, so hopefully that will suffice.

Yes, I think just documenting it should suffice.
