### ISSUE TITLE
Trouble with `defreader` inside other forms

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hy#2303]
Consider

```
(do
  (defreader r 5)
  (print #r))
```

The result is `LexException: reader macro '#r' is not defined`. Perhaps `defreader` shouldn't be legal here in the first place, but [what's checked in `defreader`](https://github.com/hylang/hy/blob/a58129205adca5c076597c4fa8d694b109f9d025/hy/core/macros.hy#L94) is whether we're in the global scope, which we clearly are. What's more, that check doesn't seem to work, because the same error message as above is produced when you use a `defn` instead of `do`.

**Comment by scauligi** [comment]
The reason this happens is because `read-many` parses a complete top-level form before handing it off to the compiler, so it tries to read the entire `do` block all at once.

The global scope check does work, but in this case never fires since we never even get to the compile stage; the reader tries to read the whole thing in one go and trips over the `#r` before anything makes it to the compiler.

Technically working as intended, so this might be a doc-me-bro instead.

**Comment by Kodiologist** [comment]
> The global scope check does work, but in this case never fires since we never even get to the compile stage; the reader tries to read the whole thing in one go and trips over the `#r` before anything makes it to the compiler.

```
(do (defreader r 5))
(print #r)
```

Tricky. I didn't think this through. Yeah, a warning in the manual could make sense.

Do you think code like `(do (defreader …) …)` should be forbidden, although it works if you don't try to call the reader macro thus defined in the same top-level form?

**Comment by scauligi** [comment]
There isn't currently an easy way of detecting a top-level form vs an inner form; I could potentially add a new variable in the compiler that tracks what "level" its compiling at (or even just a flag "was-I-already-compiling"), but I'm not sure how useful it would be outside of this gotcha?

**Comment by Kodiologist** [comment]
Yeah, I suppose that would be overkill.
