### ISSUE TITLE
`~@ #* …` produces a weird result instead of an error 

### ISSUE THREAD

**Issue by z80dev** [hylang/hy#2336]
```lisp
(defmacro condp-1 [op obj #*body]
  `(cond
     ~@(lfor [val res] (by2s body)
         `((~op ~obj ~val) ~res) )))

(defmacro condp-2 [op obj #*body]
  `(cond
     ~@(unpack-iterable (lfor [val res] (by2s body)
              `((~op ~obj ~val) ~res) ))))

(.macroexpand-1 hy (.read hy "(condp-1 < 10 100 12 1000 123 10000 0 120000 1)"))
(.macroexpand-1 hy (.read hy "(condp-2 < 10 100 12 1000 123 10000 0 120000 1)"))
```

The macroexpansion I want to get is 
```lisp
(cond (< 10 100) 12 (< 10 1000) 123 (< 10 10000) 0 (< 10 120000) 1)
```

instead I'm getting, from condp-1 and condp-2 respectively:

```lisp
;; condp-1
'(cond ((< 10 100) 12) ((< 10 1000) 123) ((< 10 10000) 0) ((< 10 120000) 1))

;; condp-2
'(cond (< 10 100) 12)
```

The first has inner expressions nested a level too deep. The second is missing elements.

Am I missing something about how unpack-iterable works? From testing its behavior, this is the only scenario where I found it to not return all members

**Comment by Kodiologist** [comment]
I get `NameError: name 'by2s' is not defined` when I try this.

**Comment by z80dev** [comment]
@Kodiologist sorry about that, I left out the import from hyrule

```lisp
(import hyrule.collections [by2s])
```

**Comment by Kodiologist** [comment]
Oh yeah, you should know that that's a private function that appears in the Hyrule manual due to a bug (https://github.com/hylang/sphinxcontrib-hydomain/issues/18). Use `toolz.partition` instead, or just copy the definition of `by2s` into your own code.

Well, I see no Hy bug in how `condp-1` works. The `lfor` returns two-element expressions, so that's what you get in the result. A simpler example of the same thing is that `` `[~@(lfor  x (range 3)  [x x])]`` returns `'[[0 0] [1 1] [2 2]]`.

`condp-2` seems pathological since you're doing `~@ #* …`, but `~@` always requires exactly one argument, so why unpack? Hy doesn't expect a `#*` here and so it does something nonsensical. We could get a better error message by changing the code that checks the arguments of `~` and `~@` to reject `#*`, but I suspect there are a lot of pathological places you could use `#*`, and it's probably not worth checking explicitly for all of them. I'm not sure what the right approach is here.
