### ISSUE TITLE
Improve REPL outputs

### ISSUE THREAD

**Issue by glyh** [hylang/hy#2340]
```hy
'(+ 1 1) 
; expect: (+ 1 1)
; actual: '(+ 1 1)
```

```hy
(and 1 (print 2))
; expect: None, with stdout "2"
; actual: Only stdout "2"
```

**Comment by Kodiologist** [comment]
The actual results are what I expect and what is intended. If you think they're incorrect, explain why.

**Comment by glyh** [comment]
Common Lisp:
```
'(+ 1 1) ; => (+ 1 1)
(and 1 (format t "1")) ; => stdout: "1\n", return NIL
```

**Comment by Kodiologist** [comment]
I know that other Lisps do different things, but that's not much of an argument for what should be done. `(hy.repr '(+ 1 1))` returning `"'( + 1 1)"` means that the input round-trips properly; by contrast, `(+ 1 1)` would return `2`. There's no sense in making the user figure out whether manually adding a quote is necessary in order to get round-trip evaluation.

By the way, you know you can use your own REPL output function with the `--repl-output-fn` argument to `hy`, right? You're not locked into `hy.repr`.

> The language is functional any way so I don't think dropping nones and pretend it's using some statements rather than expressions are "functional".

It's not much of a pretend game when our behavior of eliding of `None` is inherited directly from Python, and we do it consistently regardless of how the `None` is produced. Showing every `None` would create a lot of terminal spam, since lots of forms return `None`. It's easy to understand once you realize that `None` is elided unconditionally and not just when it's produced from "statement-like" forms.

> Also, hy's behavior on the second case is ambiguous, making people think it's returning values instead of printing strings.

A bit of experimentation should dispel any doubts:

```
=> 1 (print 2)
2
=> (print 2) 1
2
1
=> None
=> 
```
