### ISSUE TITLE
How do we type-check Hy code?

### ISSUE THREAD

**Issue by SamB** [hylang/hy#2341]
While https://github.com/hylang/hy/pull/1810 added support for type annotations to Hy's compiler, this doesn't give us adequate means to run Hy code through a type-checker.

* You might hope that the checker would just import the module and hy's import hook would just make things work, but they don't import modules, presumably because:
  * That would involve arbitrary code execution
  * Some checkers (Pyright, Pyre) aren't written in Python
  * Some type info (local vars, signatures in comments) doesn't make it into the bytecode
  * Bytecode isn't exactly a stable API
* You could run hy2py over your code, but then the line references will presumably be wrong.

**Comment by Kodiologist** [comment]
Good question. Type annotations are a corner of Python I have little experience with because of their strange role in the language: there's lots of syntax for them, and Python supports introspection of them, but Python itself doesn't do any typechecking, so the real work of designing and implementing the feature is left to third parties, who in general don't agree with each other.

If the typecheckers require Python source code as text, and can't use `ast` objects, then it seems you have to use `hy2py`. And if you have to use `hy2py`, we can't get the line numbers right, because Python is whitespace-sensitive and doesn't implement JavaScript-style source maps.
