### ISSUE TITLE
Summary of functions and macros in API documentation

### ISSUE THREAD

**Issue by wrobell** [hylang/hy#2488]
It is quite hard to navigate current API documentation.

It would be great to add a summary at the beginning of each API subsection (https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html#directive-autosummary). Some examples

- https://scikit-learn.org/stable/modules/classes.html
- https://numpy.org/doc/stable/reference/routines.array-creation.html
- https://wrobell.dcmod.org/rbfly/api.html (my own project)

Splitting core macros could help as well, i.e. iterating macros like `lfor`, `gfor`, etc. could have their own section.

**Comment by Kodiologist** [comment]
Even if somebody was willing to put in the effort, they'd have to write the summary table manually for most macros, because most macros are documented directly in `ast.py` rather than with docstrings. That would lead to the summaries and the full documentation for each macro getting desynchronized when somebody edits one and forgets to update the other. If we converted these passages to docstrings, on the other hand, `result_macros.py` would be annoyingly massive (like, more than it already is).

**Comment by wrobell** [comment]
Thanks for the explanation.
