### ISSUE TITLE
let, lambda and scope of bindings

### ISSUE THREAD

**Issue by wrobell** [hylang/hy#2507]
I can reference a binding in a lambda defined under let
```
(setv test-let-a
  (let [start 0]
    (fn []
      (setv result (cut "abcdefg" start (+ start 4)))
      result)))

(test-let-a) ; "abcd"
```
But I cannot update it
```
(setv test-let-b
  (let [start 0]
    (fn []
      (setv result (cut "abcdefg" start (+ start 4)))
      (+= start 1)
      result)))

(test-let-b) ; UnboundLocalError: cannot access local variable 'start' where it is not associated with a value
```
Using `nonlocal` does not seem to help
```
(setv test-let-c
  (let [start 0]
    (fn []
      (nonlocal start)
      (setv result (cut "abcdefg" start (+ start 4)))
      result))) ; SyntaxError: no binding for nonlocal '_hy_let_start_78' found
```
I might misunderstand something, or a bug?

Documentation says
> Basic assignments (e.g. setv, +=) will update the local variable named by a let binding when they assign to a let-bound name.

Therefore `test-let-b` shall work?

**Comment by Kodiologist** [comment]
I think this behavior is intentional. Consider this simplified case:

```hy
(let [x 0]
  (fn []
    (setv x 1)))
```

This compiles to:

```python
import hy
_hy_let_x_1 = 0

def _hy_anon_var_2():
    x = 1
```

because, per Python, assigning to a variable in a function, without an accompanying `nonlocal` or `global`, implies that you want to assign to a variable local to that function. If you add `(global x)` before `(setv x 1)`, then the assignment happens to the `let` variable as desired. `(nonlocal x)` won't work because `x` is global, not local to a containing function. But having to refer to `x` as global does feel strange considering that it's not meant to be accessible outside the `let`.

@scauligi What say you?

**Comment by Kodiologist** [comment]
No, actually, `global` doesn't work, either. This

```
(let [x 0]
  (fn []
    (global x)
    (setv x 1)))
```

compiles to

```
import hy
_hy_let_x_1 = 0

def _hy_anon_var_2():
    global x
    x = 1
```

Something is definitely wrong.

**Comment by Kodiologist** [comment]
Yes, because that's the first reference to the variable. You can see it in `hy2py`.

**Comment by wrobell** [comment]
> Yes, because that's the first reference to the variable. You can see it in `hy2py`.

`test-let-a` references `start` as well, but it does not raise an error about unbounded variable.

**Comment by scauligi** [comment]
Aha, so looks like this is an edge case that happens only when the `let` is in (Pythonic) global scope.
Since the `let` form ends up creating variables that are in Python's global scope, it's an error (per Python semantics) to use `nonlocal`. However, per _Hy's_ semantics, `global` cuts through all `let` forms, so using `global` is also incorrect.

If you stick the `let` inside of a dummy function then everything works again:

```hy
(setv test-let-c
      ((fn []
         (let [start 0]
           (fn []
             (nonlocal start)
             (setv result (cut "abcdefg" start (+ start 4)))
             (+= start 1)
             result)))))
(print (test-let-c))  ; -> abcd
(print (test-let-c))  ; -> bcde
```

but this sucks and nobody wants to do that.

[At one point in the scoping PR](https://github.com/hylang/hy/pull/2125#issuecomment-886412625) I had implemented a feature to compile the `nonlocal` form to `global` when necessary, but I removed it to keep the PR focused on `let` (and then promptly forgot about it). It also had some nuances which made it non-trivial to implement correctly. But nonlocal-to-global would fix the global-let issue and make `test-let-c` work.

---

> `test-let-b` vs `test-let-c`

The semantics of `let` in Hy are meant to mimic Python assignment (`setv`) as much as possible. Keeping to that means `test-let-b` won't work, since the assignment inside the function implicitly creates a new variable.

However, I wouldn't be opposed to changing the semantics of Hy `let` to allow for `test-let-b`-style semantics, ie `let`-bound names never need to be declared `nonlocal`.
Pros: Would allow code like `test-let-b`, don't need to implement the nonlocal-to-global feature
Cons: Binding a name with `let` makes it difficult to shadow it later, unless you use another `let` (but maybe that's really a pro?) Eg:

```hy
;; (assuming proposed test-let-b-style semantics)
(let [start 0]
  (defn not-shadow []
    (setv result "")
    (for [start (range 4)]  ; oops, I wanted "start" to be its own local variable
      (+= result (cut "abcdefg" start (+ start 4)))
      (+= start 1))
    result)
  (print (not-shadow))
  (print start))  ; -> would print 4 instead of 0
```

**Comment by wrobell** [comment]
When creating this ticket, I was hoping for `test-let-b`. Not sure anymore - `test-let-c` is more explicit.

Python does not want modifying a variable from outer scope by default (thus `nonlocal` and `global`). But looking at docs of various Lisps - `test-let-b` is the way, and examples suggest to use nested `let` for shadowing, indeed.

Clojure seems quite interesting in this context. Variables are immutable, so you need to use atoms and `swap!`, see for example https://clojuredocs.org/clojure.core/let#example-5436eaa4e4b0ae795603157c. This makes modifying of a let binding very transparent.

Maybe Hylang could eat its cake (being a Python) and have it at the same time (being a Lisp) by allowing modification of variable from outer scope with a special macro like Clojure (accidentally?) does.

**Comment by scauligi** [comment]
> When creating this ticket, I was hoping for `test-let-b`. Not sure anymore - `test-let-c` is more explicit.

After playing with this for a bit, I think `test-let-c` is the way to for us to go in Hy, since it's more consistent with Python's scoping model. Although it may break away from how other Lisps work, from what I've seen of Hy's past choices, we usually lean towards Pythonic over Lispy when we need to choose.

**Comment by Kodiologist** [comment]
Trying to work with Python's scoping is typically less painful than trying to work against it. It's not the best scoping model, but it's what we got.
