### ISSUE TITLE
fix macro require

### ISSUE THREAD

**Issue by agentultra** [hylang/hy#273]
Require'd macros cannot reference global namespace of their module

```
;; mac.hy
(defn foo [a]
  [a])

(defmacro bar [baz]
  (quasiquote
    (do (foo (unquote baz)))))

;; bang.hy
(require mac)

(bar "boop")

;; Results in:
;; NameError: global name 'foo' is not defined
```

Which is not terribly useful.

**Comment by Kodiologist** [comment]
I think the way macros and modules play together is now firmly established enough that we can say this isn't a bug. If you want the expansion of `bar` to be able to refer to a function `foo` defined in `mac.hy`, you need to include `(import [mac [foo]])` or something in that expansion. Otherwise, how could Hy tell that by `foo` you meant `mac.foo` instead of `bang.foo`?
