### ISSUE TITLE
let syntax

### ISSUE THREAD

**Issue by rcarmo** [hylang/hy#367]
Following up on a Twitter discussion, please consider supporting a more Clojure-like let syntax without the need for double brackets (I understand there were some constraints in the past, but I keep banging my head into this when switching between LISPs)

**Comment by gilch** [comment]
I'm not completely sure what makes the `with` form unparse-able, but can't we handle this in a way analogous to `&optional` in function definitions? Or to `:as` in imports?

For comparison, the Common Lisp-style, what we're using now:
`(with [[cm (Clamm)] [(Class)]] ...)`

Using the `&optional`-style, the inner `[]` are *only* required when there's an "as" `target`. Otherwise, it gets the default name:
`(with [[cm (Clamm)] (Class) ] ...)`
Remember we already do something like this for function bindings.

Using import `:as`-style, the expression following the `:as` is the `target`, the one after that (if any) is the next `with_item`.
`(with [ (Clamm) :as cm (Class) ] ...)`
This translates pretty directly to Python.

Either of these options would be unambiguous, and wouldn't come with the cost of abandoning the original Clojure-style bindings in the rest of the language for consistency.

**Comment by Foxboron** [comment]
Closing this issue in favor for #713 and adding it to the current cleanup milestone
