### ISSUE TITLE
Hy Doesn't Use Absolute Imports (breaks PEP 328)

### ISSUE THREAD

**Issue by xcthulhu** [hylang/hy#583]
The following tests fail if you put them in `tests/native_tests/language.hy`, because Hy will try to import the module `tests/native_tests/math.hy` rather than the library module

``` hy
  (import math)
  (let [[cos math.cos]
        [foo-cos (fn [x] (cos x))]]
    (assert (= (cos math.pi) -1.0))
    (assert (= (foo-cos (- math.pi)) -1.0))
    (let [[cos (fn [_] "cos has been locally rebound")]]
      (assert (= (cos cos) "cos has been locally rebound"))
      (assert (= (-> math.pi (/ 3) foo-cos (round 2)) 0.5)))
    (setv cos (fn [_] "cos has been rebound by setv"))
    (assert (= (foo-cos foo-cos) "cos has been rebound by setv")))
```

**Comment by Kodiologist** [comment]
The following works:

    $ mkdir d
    $ touch d/__init__.py
    $ echo '(print "hello from math.hy")' > d/math.hy
    $ echo '(import math) (print (math.sqrt 2))' > d/test.hy
    $ hy d/test.hy 
    1.4142135623730951

Creating a test file `tests/native_tests/math.hy` doesn't work with the new pytest-based testing infrastructure. Ultimately, this seems to be because the method `pypkgpath` in pytest assumes that packages have to have a file `__init__.py` in them, rather than, say, `__init__.hy`. I doubt this is worth trying to "fix" on the pytest side, and it's easy enough to avoid on the Hy side by not giving any of our test files the same name as a standard module, which is a bad idea anyway.
