### ISSUE TITLE
Implement a -OMG-FAST mode

### ISSUE THREAD

**Issue by olasd** [hylang/hy#60]
Since hy is basically creating an AST from scratch, it should be fairly easy to leverage something along the lines of https://pypi.python.org/pypi/astoptimizer to trim it along the way.

Of course, this should be made unpluggable, as manipulating the generated AST could impact debugging.

(ticket name courtesy of @paultag)

**Comment by Kodiologist** [comment]
astoptimizer is no longer maintained, and its successor, fatoptimizer, is unstable and doesn't seem to be particularly effective (yet). Meaningful optimizations to Hy are always helpful, but hopefully they'll all be of the sort with no downsides that we can enable all the time, instead of requiring the user to enable them explicitly.
