### ISSUE TITLE
Split hy/contrib into own repo as hy.contrib

### ISSUE THREAD

**Issue by Foxboron** [hylang/hy#629]
Take the current `hy/contrib` folder and split it into a own repo, leaving a git submodule.
The basic idea is to delegate the workload from the main hy repo, and lessen the entry level of contribution. We also get much more flexibility inside contrib to make rapid changes and do more iterative development (if wanted).

Steps to success:
```
22:59      paultag  : action items:
22:59      paultag  : 1) git filter-branch + love => hy.contrib to a new repo
22:59      paultag  : 2) new hy.contrib repo
23:00      paultag  : 3) hy.contrib manager / policy 
23:00      paultag  : 4) migrate bugs
23:00      paultag  : 5) coordnate tag / release system
23:00      paultag  : 6) document git checkouts 
```

Opinions, rate or hate?

**Comment by algernon** [comment]
:-1:, the traffic on contrib is low, yet, getting code into hy is easy, so I do not see the point of moving contrib out of Hy at this time. And submodules are a huge pain, that'd just make contrib much more newcomer unfriendly.

Since the downsides are numerous, and upsides are few, how about we close this issue without doing anything? :)

**Comment by kirbyfan64** [comment]
It's also worth noting submodules are usually more trouble than they're worth. Nim recently made the C sources a submodule, only to remove it a few days later.

**Comment by Foxboron** [comment]
I'll just close this and review it if it some how becomes an issue later.
