### ISSUE TITLE
Reimplementing let

### ISSUE THREAD

**Issue by kirbyfan64** [hylang/hy#688]
I just got these two super-crazy ideas for reimplementing let, both of which solve #664. I'd be happy to open a PR if one of them works out.

1. Implement let as a try block. This:

```clojure
(let [[a 1] [b 2]]
    ...
)
```

would compile to:

```python
try:
    a = 1
    b = 2
except: raise
finally:
    try:
        del a
        del b
    except NameError: pass
```

This wouldn't change the current behavior, as far as I know. It could be a nice alternative to context managers. There wouldn't be any issues with assigning outer variables.

Speaking of context managers...

2. Use with blocks

The let block shown above would turn to:

```python
with hy.contexthelper(1) as _hy_let_var_a, hy.contexthelper(2) as _hy_let_var_b:
    a = _hy_let_var_a.value
    b = _hy_let_var_b.value
    ...
```

where contexthelper could be defined like this:

```python
class contexthelper():
    def __init__(self, v):
        self.value = v
    def __enter__(self):
        if hasattr(self.value, '__enter__'):
            self.value.__enter__()
    def __exit__(self):
        if hasattr(self.value, '__exit__'):
            self.value.__exit__()
        del self.value
```

This could break code because of scoping, but it would mix scoping and context managers for a nice combination, most particularly for things like file objects.

Thoughts?

**Comment by farhaven** [comment]
I have another suggestion:

```
(defmacro let+ [vars &rest body]
  "Executes `body` in the lexical scope described by `vars`."
  "Warning: This litters in the current scope, use wisely!"
  (defn replace-symbols [expr m]
    (assert (instance? (, HyExpression tuple) expr) (type expr))
    (setv rv (HyExpression))
    (for* [i expr]
      (.append rv (if (and (instance? HySymbol i) (in i m))
                    (get m i)
                    (if (instance? HyExpression i)
                      (replace-symbols i m)
                      i))))
    rv)
  (setv syms {})
  (setv init (HyExpression))
  (for* [v vars]
    (if (instance? list v)
      (do
        (if (!= (len v) 2)
          (macro-error v "Scope lists must have exactly two items"))
        (if-not (instance? HySymbol (first v))
          (macro-error v "First item in scope lists must be a symbol"))
        (setv (get syms (first v)) (gensym (first v)))
        (.append init `(setv ~(get syms (first v)) ~(second v))))
      (if (instance? HySymbol v)
        (do
          (setv (get syms v) (gensym v))
          (.append init `(setv ~(get syms (first v)) None)))
        (macro-error v "Scope items must be lists or symbols"))))
  (setv body (replace-symbols body syms))
  `(do
     ~@init
     ~@body))
```

This one works by generating a new symbol for each variable and replacing all references in `body` with the new symbol.

With this, nested `lets` work, which fixes #664. It also fixes `(break)` inside loops that look like this:

```
(while True
  (let []
    (break)))
```

The downsides are that it needs `gensym`, which isn't available for macros in `hy.core.bootstrap`. One way around this would be to use the UUID module instead, or moving `gensym` to `bootstrap`. While we're at it, we could modify `gensym` to use the UUID module instead of using a lock to protect the symbol counter: ```(defn gensym [&optional x] (HySymbol (str (uuid.uuid4))))```

The other downside is that this "litters" in the current scope because it doesn't `del` symbols it created. This is only an issue if you're using `let` on the top level though, we can rely on the scope provided by functions if we're using `let` inside macros/functions. Not calling `del` on the symbols is needed for stuff like

```
(def foo
  (let [[x 'bar]]
   (fn [] x)))
````

to work. Deleting the generated symbol for `x` would cause a name error to be raised whenever `foo` is called.

Does this make sense as a PR?

**Comment by tianon** [comment]
@paultag just to confirm your point:
```console
$ docker run -it --rm hylang/hy
hy 0.11.0 using CPython(default) 3.4.3 on Linux
=> (let [[x 1]] (let [[x 2]] (print x)) (print x))
2
1
```

(ie, the example you provided does work today)

**Comment by algernon** [comment]
*pokes stuff*

One of the most important stuff in the Grand Language Cleanup is let. I like some of the things here, so... how can I help make this go forward?

**Comment by gilch** [comment]
Running with @farhaven's suggestion, what possible good does renaming the bindings to gensyms do? I mean as opposed to just using a `setv`. The answer: it creates the illusion of the variables leaving scope. I think that's about it, but please tell me if I missed another advantage over `setv`. This is just an illusion, though, and it litters the namespace with gensyms. Like just using `setv`, it doesn't break statements like `yield` `continue` `break` etc.

Since farhaven has just demonstrated the feasibility of mangling the symbols inside the `let` body, how about this instead?

First, make an empty object type we can assign attributes to:
```Python
class namespace(object):
    pass
```
Then, and this is the trick, `let` will mangle the symbols to contain a `.`. Starting with that last example:
```Hy
(def foo
  (let [x 'bar]  ; new let ditches extra brackets.
   (fn [] x)))
```
Would expand to:
```
(def foo
  (do
    (setv _hy_anon_var_1 (namespace)
          _hy_anon_var_1.x 'bar)
    (fn [] _hy_anon_var_1.x)))
```
This still litters `_hy_anon_var_`s, but Hy was doing that *anyway*. It might even be safe to use at the module level. This way we don't need `gensym`, and `let`s with multiple bindings only create one new variable, instead of many:
```Hy
(let [x 1 y 2 z 3] (print x y z))
```
Becomes
```Hy
(do
  (setv _hy_anon_var_1 (namespace)
        _hy_anon_var_1.x 1
        _hy_anon_var_1.y 2
        _hy_anon_var_1.z 3)
  (print _hy_anon_var_1.x _hy_anon_var_1.y _hy_anon_var_1.z))
```

Furthermore, unlike gensyms, we could use this kind of mangling to support a kind of nonlocal in Python2.
```Hy
(defn make-counter []
  (let [count 0]
    (lambda [] (setv count (inc count)))))
```
Which expands to:
```
(defn make-counter []
  (do
    (setv _hy_anon_var_1 (namespace)
          _hy_anon_var_1.count 0
    (lambda [] (setv _hy_anon_var_1.count (inc _hy_anon_var_1.count)))))
```
This works because the entire `lambda` is in the body of the `let` macro, so its symbols get mangled too. Python lets you *read* variables in enclosing scope, you just can't *assign* to them. *Mutating* `_hy_anon_var_1` doesn't count as an enclosing scope assignment!

**Comment by algernon** [comment]
I like where this is going. Will have a stab at it today.

**Comment by algernon** [comment]
I had a go at this, and found a few complicating issues:

* `instance?`, `first`, and `defn` are not yet available at bootstrap, so you can't use that in the macro definition.
* `gensym` is problematic... it should be moved to bootstrap if we want to use it from `let`... but it is easier to use `uuid` instead then.
* `replace-symbols` needs to do a deep walking, and traverse into lists and dicts too, otherwise things will break:

```hy
(let [[citer (iter coll)]]
  (for* [v citer]
    ...))

(let [[x 1]]
  {:x x})

(defmacro zing [] `x)
(let [[x 1]] (zing))
```

These all work currently, but wouldn't with @farhaven's `replace-symbols`

**Comment by algernon** [comment]
You pretty much need `hy.contrib.walk` for this, and some heavy rewriting. The most problematic part is the last one, where you use a macro within let. You can't rewrite that without expanding the macro first.

**Comment by gilch** [comment]
> not yet available at bootstrap

`let` will not be a simple macro. Putting it in bootstrap will only make it harder. But we don't need it in bootstrap. Put it late in core, or even in contrib. Then redefine core to use `setv` in place of `let`.

> and traverse into lists and dicts too

Have you tried it? I thought my `xi` form would have a similar problem, but it only has to traverse `HyExpression`s that *expand* into dictionaries and lists, not the collections they ultimately produce.

Observe:
```Hy
=> (flatten {1 10 2 20 3 30})  ; dict iter only gets keys
from hy.core.language import flatten
flatten({1: 10, 2: 20, 3: 30, })
[1, 2, 3]
=> (flatten '{1 10 2 20 3 30})  ; note the quote
from hy.core.language import flatten
from hy import HyDict, HyInteger
flatten(HyDict((((((([] + [HyInteger(1)]) + [HyInteger(10)]) + [HyInteger(2)]) +
 [HyInteger(20)]) + [HyInteger(3)]) + [HyInteger(30)])))
[1, 10, 2, 20, 3, 30]
```
Why does the quoted form work? Because `flatten` is traversing an expression, not the dictionary that expression would produce.

> The most problematic part is the last one, where you use a macro within let. You can't rewrite that without expanding the macro first.

Then expand the macro first. Make `let` recursively apply `macroexpand` on any macros it finds in its body, before mangling symbols. It would certainly not be the first macro to do this kind of thing. I think I've seen this done before in Common Lisp.

**Comment by kirbyfan64** [comment]
For some reason, I feel like recursively traversing the Hy AST is a super bad idea. You're going to have to implement all of Python's scoping rules:

```hy
(let [x 1]
  (print x) ; prints 1
  ((fn [] (global x) (def x 2) (print x))) ; prints 2
  (print x)) ; prints 1
```

**Comment by gilch** [comment]
Ugh, `global`s. I hadn't thought of that. `nonlocal` would also break. Please tell me if I misses any other cases.

For `let` to work, it would have to avoid mangling exactly the symbols `global` or `nonlocal` apply to. But it would still have to mangle `nonlocal` if the variable referred to is also inside the `let`. It could be done. There are deterministic rules, and Python does it. But yeah, that's re-implementing Python's scoping rules. Not exactly sure how hard that would be.

The easy way out would be to disallow `nonlocal` and `global` from appearing in a `let` if they apply to symbols `let` is using. The `let` would just raise an error and refuse to compile. I don't really like it, but it would be easier to just detect this case than to fix it. I suppose we could do it this way first, and think about supporting `global`/`nonlocal` later.

**Comment by kirbyfan64** [comment]
@gilch With all those restrictions, though, this'll probably end up just as confusing as what's there right now...

**Comment by gilch** [comment]
"With all those restrictions"? `global` is not even used that much. And you *can* still use `global`, just not if `let` is already using that symbol. With a good error message, you could easily fix it in most cases by making `let` bind some other symbol instead. Similarly with `nonlocal`. In fact, if `nonlocal`s target appears *inside* the body of the `let` you don't even need the `nonlocal` keyword, because `let` already does the lexical scoping for you. 

I still think it's a dramatic improvement over the old `let`. While the `let` macro may be complex, the expansion is rather simple. `yield`,`break`, and `continue` will work, while they wouldn't inside of a function, and this would be extremely difficult with that approach. `nonlocal` is not even available in Python 2, and this `let` would give you that kind of capability.

Actually I wonder if it would be better to have two versions of `let`. The Python2 version would use the namespace objects and dot mangling as discussed, while the Python3 version would just `nonlocal` its bindings.

**Comment by kirbyfan64** [comment]
But you still have lambda arguments to worry about...

I wasn't in favor of it before, but now I'm starting to agree that removing `let` may be a good idea.

**Comment by gilch** [comment]
> But you still have lambda arguments to worry about...

Not sure what you mean, can you show me an example?

**Comment by kirbyfan64** [comment]
```hy
(let [x [1 2 3]]
  (map (fn [x] (inc x)) x))
```

**Comment by gilch** [comment]
And a naive implementation expands into
```Hy
(do
  (setv _hy_anon_var_1 (namespace)
        _hy_anon_var_1.x [1 2 3])
  (map (fn [_hy_anon_var_1.x] (inc _hy_anon_var_1.x)) _hy_anon_var_1.x))
```
But to get the old behavior, needs to be
```Hy
(do
  (setv _hy_anon_var_1 (namespace)
        _hy_anon_var_1.x [1 2 3])
  (map (fn [x] (inc x)) _hy_anon_var_1.x))
```
Again, easier to detect and raise error than to fix. But, I agree, this restriction is much more serious than for `global`. It would be more worthwhile to fix it in the macro.

The fix given an error would be the same: change the name of the `let` binding.
```Hy
(let [xs [1 2 3]]
  (map (fn [x] (inc x)) xs))
```
```Hy
(do
  (setv _hy_anon_var_1 (namespace)
        _hy_anon_var_1.xs [1 2 3])
  (map (fn [x] (inc x)) _hy_anon_var_1.xs))
```

**Comment by algernon** [comment]
> Have you tried it?

Yes. That's why I listed it as a problem. Mind you, perhaps my implementation was lacking. I'll push what I have onto a branch on ~monday.

**Comment by gilch** [comment]
A sketch of how the dot-mangle `let` macro might work:

The bindings part is easy:
+ create a `do` block around a `setv` for a namespace instance to a generated variable, and dot-mangle the let bindings to that namespace variable. As in my examples.
+ remember the binding-symbols for later.

The body part is not easy:
+ recursively pre-expand macros in its body
+ deep-traverse code, mark binding-symbols affected by `global`
+ deep-traverse code, mark binding-symbols affected by `nonlocal`
+ deep-traverse code, mark binding-symbols that are parameters in a fn.
+ deep-traverse code, mark binding-symbols that are parameters in a lambda.
+ deep-traverse code, replacing each of the unmarked binding-symbols with the dot-mangled equivalent.
+ deep-traverse code, unmark any marked symbols.
+ append new body to `do` form and return it.

Marking merely has to be reversible. You could replace with a gensym prefixed symbol. Or if Hy symbols allow any kind of metadata or Python setattr, you could mark it that way, again, more safely with a gensym.

*How* you detect which symbols are affected by `global`, `nonlocal` or are parameters is the interesting question. The Python compiler does it. And it's open-source, so we can look. I'm not sure if AST has useful metadata for this kind of thing, but if it does, this might be easier to implement at the Python level.

**Comment by gilch** [comment]
> I wasn't in favor of it before, but now I'm starting to agree that removing let may be a good idea.

@kirbyfan64 I agree, but I'm not the one you need to convince. @algernon closed #844, based on what appeared to be a loose consensus in a discussion with nine other participants besides us three.

The issues I pointed out in #844 are still a problem. A function is not just a block scope. It can also sever multi-part control statements in surprising ways. As implemented now, a `break` or `continue` won't work inside a `let` unless the entire loop is inside the `let`. Worse, a `yield` *will* work inside a `let`, but doesn't do what you want unless the entire generator function is inside the `let`.

Therefore we *can't* use a function to implement `let`.

Furthermore, `let` is supposed to be able to create closures, but only a function can do this in Python. 

Therefore we *must* use a function to implement `let`.

But closures in Python don't even work like closures in Lisp. You can't assign to the closed-over variable. It's read-only. You could get around this with `nonlocal` but that doesn't work in Python2. Actually in Clojure it's also read-only. If you want to mutate something like that you would use an "atom", which would not be hard to implement in Python2 (I've pretty much done it in DRYthon).

So, given that we *can't* use a function and *must* use a function, what are the options?
 * Get rid of `let`. Use a `setv` or nested class declaration instead, or explicitly create and call a lambda.
 * Make a version of `let` that uses a function and another that doesn't. Call them something else to avoid confusion. (So we still get rid of `let`).
 * Re-implement `break`, `continue` and `yield` so they aren't severed from their containing statement by functions. I've pretty much done this with exceptions in DRYthon for `break` and `continue` (and `return`). They work with labels now too. `yield`, though, is going to be tricky. I once implemented a Python-like `yield` in Java using threads. Something like that might work. Perhaps it would only need co-routines (i.e. using the generator's `.send()`), but I'm not sure how to do it that way.
 * Re-implement closures without using functions, or at least not directly. I'm not sure how to do this either.
 * Make `let` a complicated macro that always expands into a generator function, plus any bridge code to make it work like the old `let`, and to make `break/continue/yield` work.
 * Get rid of `break/continue` and refactor loops to use `if/cond` or explicit exceptions. Get rid of `yield` and refactor generators into Haskell-like compositions with `itertools`, and/or implement Clojure's lazy-seq macros? Use an explicit Clojure-like "atom" instead of `nonlocal` where required.

**Comment by davexunit** [comment]
Complete Hy noob here, but why does "explicitly create and call a lambda" not have the same issues as `let`, given that `let` in every Lisp I know can be implemented as syntactic sugar for the corresponding lambda expression?

**Comment by kirbyfan64** [comment]
@davexunit Because of Python 2's variable scoping:

```hy
(defn outer []
  (setv x 1)
  (defn inner []
    (setv x 2))
  (inner)
  x)
(outer) ; returns 1, NOT 2
```

**Comment by cwebber** [comment]
Is it just Python 2?  Could we just make a Python 3 version of "let" only and have it be sane?

I don't think clean language design should be held back by Python 2.

**Comment by gilch** [comment]
No, Python3 gives us `nonlocal`, but it doesn't help with `break/continue/yield`. `nonlocal` isn't even the biggest problem. Clojure's "vars" are also effectively read-only. If you need to change an identity in an enclosing scope in Clojure, you'd use an "atom", not a "var", and mutate the "atom" rather than overwriting it. We can do that in Python2 with a single-item list.

> Complete Hy noob here, but why does "explicitly create and call a lambda" not have the same issues as let

@davexunit: It **does** have the same issues, since that's pretty much how `let` works now. The difference (and it's a big difference) is that if you do it explicitly, you expect it to work like Python, so you aren't *surprised* when a `yield` *automagically* turns the inner function into a generator, but if you use `let`, you expect it to work more like a block-scoped local variable (because `let` is how that's done in Lisp) which just doesn't *do* that.

Similarly for severing `break` or `continue` from its containing loop. If all you wanted was a "local variable", this is *surprising* behavior. If we got rid of `let`, no-one would attempt to use a function just to create a local, they'd just use a `setv` instead (and perhaps a `del` if necessary, but with gensyms who cares?). If they really needed a closure, then the explicit approach can still do that.

**Comment by kirbyfan64** [comment]
Not going to work out. Closing.
