### ISSUE TITLE
An option for hy to *only* check syntax

### ISSUE THREAD

**Issue by kozross** [hylang/hy#689]
I'm writing a syntax checker for Hy in Flycheck at the moment, and have hit a bit of a stumbling block. At the moment, the only (easy...) way to syntax-check Hy source code is to pump it through `hy` and hope it executes. This isn't very desirable in a Flycheck checker, as it means executing (again and again) code that may take a long time to run or have side effects we don't want.

Would it be possible to add a flag to `hy` (I suggest `-c`) which only checks it for syntactic validity? It would spew the same errors as `hy` does now if the code isn't syntactically valid (or it can't find the module or whatever), and do nothing but return success otherwise?

**Comment by xificurC** [comment]
Is there anything done on this part? It's marked as `good-first-bug` but it seems like a bigger project (to write a full-blown linter)

**Comment by Kodiologist** [comment]
No, nobody has worked on this since. Presumably @berkerpeksag marked it `good-first-bug` on the assumption that you'd either use a method like Kirby suggested or use pylint. But in any case, I'd tend to think it's not a very good first bug.

**Comment by Kodiologist** [comment]
Beware that once we have reader macros, which seems likely to happen (#2242), syntactic correctness will become Turing-undecidable. That is, you'll have to compile and macroexpand everything in order to check the syntax, which can involve running arbitrary code. Perl has a similar problem due to `BEGIN` blocks.

**Comment by Kodiologist** [comment]
Yeah, considering that issue, this feature would probably not be very helpful, and it would be dangerous because people would probably use it not realizing that it can run arbitrary code. You could implement an approximation of some sort, like checking that code with no reader macros is syntactically correct in terms of what can be analyzed statically, but that's probably something best implemented as an external tool than a feature of Hy itself.
