### ISSUE TITLE
allow leaving out extra brackets in let?

### ISSUE THREAD

**Issue by brhsiao** [hylang/hy#713]
This

    (let [[a 1]
          [b 2]] 
      (print a b)) 

could be expressed as

    (let [a 1
          b 2]
      (print a b)) 

without loss of meaning.

Can we please have this? The `[[` following each `let` looks kind of bulky. Plus I like typing less!

**Comment by mpenet** [comment]
used to do a lot of CL/Scheme, but since having used clojure anything else than this style feels odd: 
```clojure 
(let [x 1 
       y 2 
       z nil]
  ...)
```

**Comment by gknapp** [comment]
Coming from Clojure, I feel the same.

**Comment by Tritlo** [comment]
You can define the following macro, and use that instead of let.

    (defmacro/g! clet [bindings &rest code]
      (setv g!argli [])
      (setv g!bindings bindings)
      (while (not (empty? g!bindings))
        (setv g!argli `(~@g!argli [~(car g!bindings) ~(car (cdr g!bindings))]))
        (setv g!bindings (cdr (cdr g!bindings))))
      `(let [~@g!argli] ~@code))


Then you can do:

    (clet [x 1 y 2]
          (print x y)
          (print y x))

**Comment by jebberjeb** [comment]
+1 removing the extra [ ]

**Comment by gilch** [comment]
+1
I understand this is easy to fix with macros, but I would prefer that the core forms like `let` be more consistent with the way we write dictionaries in Hy, like `{'x nil 'y 1}` rather than `{['x] ['y 1]}`

Guidelines say we should borrow from Python3 first, Clojure second, and Common Lisp third. 

Remember from Zen of Python: "Flat is better than nested." "Simple is better than complex." As for having to spell out `nil`, "Special cases aren't special enough to break the rules." and "Explicit is better than implicit." 

I much prefer Clojure's `let` to Common Lisp's anyway and usually use a macro that behaves that way in Common Lisp. 

Paul Graham's Arc Lisp, noted for it's conciseness, also has a [with form](https://arclanguage.github.io/ref/variables.html#with) that works more like Clojure's `let`. Arc's `let` form is even simpler: it only binds one symbol and doesn't even need extra parantheses. Most of the time when you use let you only bind one symbol, so this makes a lot of sense. It was such a good idea that I made a `let-1` macro in Common Lisp that does the same thing.
