### ISSUE TITLE
problem with the get attribute and defclass

### ISSUE THREAD

**Issue by ntrifunovic** [hylang/hy#783]
There is an error when trying to define `get` attribute of the class.

**Code:**

    (import [flask_restful [Resource]])
    
    (defclass HelloWorld [Resource]
      [[get (fn [self] "Hello World")]])

**Error:**
    
        [[get (fn [self] "Hello World")]]])
          ^--^
    HyTypeError: Can't assign to a builtin: `get'

**Flask RESTful Python example:**

    from flask import Flask
    from flask.ext import restful
    
    app = Flask(__name__)
    api = restful.Api(app)
    
    class HelloWorld(restful.Resource):
        def get(self):
            return {'hello': 'world'}
    
    api.add_resource(HelloWorld, '/')
    
    if __name__ == '__main__':
        app.run(debug=True)

**Note:** The `get` attribute can be defined using `setv` as described in  #721.

**Comment by algernon** [comment]
The problem is that we want to have two things:

* An error message when one tries to do stuff like `(defn get [&rest args] 42)` at the top level. We want this, because otherwise it'd be surprising that sometimes the built-in gets called, sometimes our function.

* Yet, we also want to allow names with builtins in cases where there's a surrounding context (such as a class)

This is hard. Hard, because the compiler - as far as I see - doesn't see the context.

**Comment by algernon** [comment]
There are a number of solutions I can imagine:

1) Teach the compiler about context. If it can walk up the expressions to see if it is under a particular form, that'd help. This has the drawback that this isn't entirely trivial. We can't just store the parsed stuff, we have to macroexpand it too. Doesn't sound pretty to me.

2) Teach `(setv)` to take a special argument, something like this: `(setv :^allow-builtins ...)`. If the flag is present, we allow deffing stuff which would otherwise shadow builtins. Then `(defclass)` could be taught to rewrite setvs and defns within itself to add an `:^allow-builtins` flag. This sounds like a bit of a hack, though.

3) Store some state within the compiler: `(defclass)` would set `self.allow_builtins` to true while compiling its body, and set it back to its original value at the end. This is a hack, but at the python level, and doesn't leak through to Hy code. Not sure it would work, though.

I'll have a stab at the third option.
