### ISSUE TITLE
"else" does not return a value from a try form

### ISSUE THREAD

**Issue by chr15m** [hylang/hy#798]
I would expect this:

```
(defn x []
  (try
    (some-call)
    (catch [e Exception] 1)
    (else 2)))
```

To compile to this:

```
def x():
    try:
        _hy_anon_var_1 = some_call()
    except Exception as e:
        _hy_anon_var_1 = 1L
    else:
        _hy_anon_var_1 = 2L
    return _hy_anon_var_1
```

But it compiles to this:

```
def x():
    try:
        _hy_anon_var_1 = some_call()
    except Exception as e:
        _hy_anon_var_1 = 1L
    else:
        2L
    return _hy_anon_var_1
```

Note that "else" does not produce a return value for the function. Same result for s/else/finally.

**Comment by farhaven** [comment]
I'd argue that `finally` is right not to return a value. In my experience it's almost always used for final cleanup operations:

```
(try
  (something-that-might-break)
  (finally
    (clean-up)))
```

We're more interested in the return value of `(something-that-might-break)` than we're interested in the return value of `(clean-up)`.

These are my 2 cents, I completely concur on `(else)`.

**Comment by zackmdavis** [comment]
@farhaven good point! 

(I had actually started working on this Issue (temporary work-in-progress commit: zackmdavis/hy@5e0c0ae3), but I'm not done yet.)

**Comment by gilch** [comment]
Let's turn to Clojure for guidance. Clojure is using Java's `try/catch/finally` exception system like Hy is using Python's `try/except/finally` statements.
```Clojure
user=> (try :foo (catch Exception e :caught!)(finally (println "FINALLY!") :returned?))
FINALLY!
:foo
user=> (try (/ 0) (catch Exception e :caught!)(finally (println "FINALLY!") :returned?))
FINALLY!
:caught!
```
We see that the `finally` form is only evaluated for side effects as `returned?` is never returned. On the other hand, the `catch` form can return a value, as in the second example, but we would lose this if `finally` returned something else. So I also agree that `finally` ought not to return its value in Hy.

I don't think Clojure has an equivalent of the optional `else` part, so that's no help. But consider that as with `do/progn`, `try` can evaluate multiple expressions for side effects and will return the value of the last one. If there are no exceptions raised, the `else` part is kind of a continuation of the `try` block in Python. Therefore, I would argue that in usual case that no exceptions are raised, the `try` should evaluate to the value of the last expression in the `else` form (if present).

**Comment by Marrin** [comment]
Just tripped over this. I agree with the interpretation of `else` as continuation of the `try` block in case no exception occurred and that the result of `else` should be the result of the `try` then.

**Comment by Kodiologist** [comment]
Tested in [`test-try-else-return`](https://github.com/hylang/hy/blob/eeb0be8fb0bdbd9d7d23dc908be2d24d4e475d0a/tests/native_tests/language.hy#L1174).
