### ISSUE TITLE
BUG: if cannot run correct

### ISSUE THREAD

**Issue by acekingke** [hylang/hy#807]
(defn total \[price amount\] 
	(* price  amount))

(if \[> (total 3 4) 100\]
	(* 0.9 (total 3 4))
	(total 3 4))
# But the result is : 
=> (defn total[price amount]
...     (* price  amount))
=> (if [> (total 3 4) 100]
...     (* 0.9 (total 3 4))
...     (* 1 (total 3 4)))
10.8
=>
=> (import hy)
=> (. hy \__version\__)
'0.11.0'
=>

**Comment by algernon** [comment]
That's because `[>` is not the same as `(>`. `[> (total 3 4) 100]` is a vector of three elements: the function `>`, the result of `(total 3 4)` and the number `100`, whereas `(> (total 3 4) 100)` would be a proper function call.

So `if` does work correctly, and does what it needs to: given that a non-empty vector is true-ish, it executes the true branch. Once you fix it, and change the vector to a list, the else branch will be run.

**Comment by acekingke** [comment]
Thank you very much， It‘s my fault
