### ISSUE TITLE
Add zackmdavis as core

### ISSUE THREAD

**Issue by berkerpeksag** [hylang/hy#820]
* Commits so far: https://github.com/hylang/hy/commits?author=zackmdavis
* Pull requests: https://github.com/hylang/hy/pulls/zackmdavis

I reviewed most of his pull requests, and they looked good to me.

So I'm +1, thoughts?

**Comment by paultag** [comment]
I'm +1; thanks for the suggestion @berkerpeksag and thank you for all you've done so far, @zackmdavis !

Really means a lot to all of us, @zackmdavis - truely! Thanks for being an awesome part of our community.

I trust his work completely, I say we grant core - let's get a PR up against the docs.

Baring objections from anyone in @hylang/core - let's do this in 3 days

**Comment by zackmdavis** [comment]
Thank you; I am honored by the nomination, and accept.

(I mean, part of me is a little nervous about the prospect of being Core of anything, because that sounds like a Responsibility that must be Lived Up To, and Hy contributions have to compete with many other possible uses of my marginal minutes. But that's true of everyone, and I was already planning on doing more Hy things on the timescale of weeks or months (like continuing the [unfinished quest](https://github.com/hylang/hy/pull/805) for full PEP 492 async functionality or taking [another](https://github.com/zackmdavis/hy/commit/2e0553c9f) shot at the Python 2 `yield-from` bugs), and I guess it couldn't hurt to add to the core-reviewer bandwidth pool during this period.)

**Comment by paultag** [comment]
Invited! Updated core.rst, welcome to Hy Soceity! Thank you!

**Comment by berkerpeksag** [comment]
Welcome Zack! :)

**Comment by zackmdavis** [comment]
:heart:

**Comment by theanalyst** [comment]
Welcome Zack
