### ISSUE TITLE
Local macros

### ISSUE THREAD

**Issue by gilch** [hylang/hy#900]
We should implement `macrolet`. That's what Common Lisp calls it, but Clojure may end up calling it `letmacro`, so we could call it that instead.

It might work by using `defmacro` named by gensym. Anywhere the macro binding symbol appears in the `letmacro` body (and in an appropriate position for macroexpansion) `letmacro` would replace it with that gensym. It should not replace the binding symbol if it appears in an inappropriate position, such as the head of a quoted Hy expression.

This approach might litter some gensyms, but without a proper `let` most uses of `gensym` will do this anyway.

Alternatively, perhaps it could be done better at the Python level, in a way similar to how `defmacro` was implemented in the first place.

**Comment by Kodiologist** [comment]
Likely better would be if `defmacro` itself was locally scoped. like `defn`. Consider the following:

```
(defn f []
  (defmacro g [a]
    `[~a])
  (g 1))

(print (f))
(defn g [a]
  (+ a 1))
(print (g 1))
```

It would be nice if Hy only used the definition of `g` in the lexical scope of the `defn`. The status quo is that `g` persists to elsewhere in the module, which can bite the unwary user if he later defines a function named `g`, as in the example. `(defn g …)` works, but subsequent `(g …)` forms call the macro instead of a function, since macros shadow functions.

**Comment by Kodiologist** [comment]
I'm inching along on a PR to make `defmacro` and `require` local when they appear in function definitions, class definitions, and comprehensions other than `for`.
