### ISSUE TITLE
`defclass` doesn't work

### ISSUE THREAD

**Issue by kevinjqiu** [hylang/hy#945]
The class definition is taken straight from the online documentation, but it doesn't work:

```
hy 0.11.0 using CPython(default) 2.7.10 on Linux
=> (defclass Cat []
...   [age None
...    colour "white"]
... 
...   (defn speak [self] (print "meow"))
... )
  File "<input>", line 1, column 1

  (defclass Cat []
  ^---------------
    [age None
  -----------
     colour "white"]
  ------------------
  
  
    (defn speak [self] (print "meow"))
  ------------------------------------
  )
  ^
HyTypeError: Wrong number of argument in defclass attribute.
```

hylang version 0.11.0

**Comment by gilch** [comment]
Yes it does work, but you're not the first to notice this "problem". (See #940, #942) We've been making changes that break backwards compatibility. 

Use the docs that match the version of Hy that you're using. Since you got Hy from PyPI, you should be using the **stable** docs. But you're reading the **latest** docs, (which would work fine if you got Hy from github). Find the green link at the bottom-left and change from **latest** to **stable**, or get the latest Hy from github.

**Comment by kevinjqiu** [comment]
@gilch Thanks!
