### ISSUE TITLE
Warning for symbols ending in ','

### ISSUE THREAD

**Issue by gilch** [hylang/hy#955]
Perhaps this belongs in Hydiomatic instead?

Symbols can end with `,` in Hy. This is almost always a mistake, `[foo, bar, baz]` when you meant `[foo bar baz]`. The former is valid in Clojure (where commas are whitespace), and required in Python. This will fail in Hy, usually because `foo,` doesn't exist. Users of Hy often also write Python at the same time, so it's really easy to make this kind of mode error. I can't be the only one this has happened to.

I'm proposing a kind of style warning to catch this kind of error.

**Comment by kirbyfan64** [comment]
IMO, the warning should only be inserted if the identifier ends up in the actual generated Python, as this might be wanted for some sort of DSL or something.

**Comment by algernon** [comment]
Hydiomatic already warns about this, provided that the symbol (without the ",") is used later in the body of the function. It only checks within `fn`, `defn`, `defmacro` and `defun`... adding `let`, `for` and a couple of other things that take bindings may be worth it. Warnings are only displayed by hydiomatic if run with the `-w` option.

I wouldn't add a warning to Hy itself, because the variable name is valid, one just has to remember that "," is part of the name, too. Mind you, there's not a lot of sane use cases for it, but still.

**Comment by Kodiologist** [comment]
Since Hydiomatic does this, I think we can close this issue.
