### ISSUE TITLE
Can you make it possible to contribute with money?

### ISSUE THREAD

**Issue by ghost** [hylang/hy#957]
I'm sure I am not the only one that would like to help out.

**Comment by Foxboron** [comment]
Interesting request. CC: @paultag @olasd 

Side note: Hei fra Bergen!

**Comment by gilch** [comment]
The question is how to distribute it fairly. I'm sure we're not the only project with this "problem", so maybe somebody has solved it. I stumbled across https://whispersystems.org/blog/bithub/ recently, which looks like an option. I have no idea how well it works in practice because it seems like it might create some perverse incentives.

**Comment by Kodiologist** [comment]
I guess the simplest approach would be to give money to @paultag and leave it up to him how to spend it. Right now, I don't think we have any hosting expenses (since we're using gratis sites like GitHub), and we can't expect to get enough donations to support a developer working full-time (that would be something like 15k USD a year at minimum). Maybe we could use money to send developers to conferences.

**Comment by asemic-horizon** [comment]
I previously offered to help draft a business model in a couple months' time when I can give it my full attention. But to use procrastination time productively, here's some informal notes that do not amount to expert advice (the standard disclaimer - I'm not currently consulting for Hy)

Because nonprofits are not naturally interfacing with market forces, they kind of have to "give shape to their own supply and demand". I'm using informal language so this doesn't come of as formal advice. But loosely:

* Supply forces -- here we have costs, developer time, etc. At first blush I don't think a full-time developer would do; rather, we'd have to review who are the stakeholders and who are the significant Hy hackers to figure out with them a model that would allow them to spend more time with Hy. In a formal project this would be preceded by an industry benchmark where we'd look at Clojure and Julia etc. to figure out what they're doing.

* Demand forces -- here we have raising awareness and establishing the importance of the project. For charities etc this involves a lot of fuzzy stuff but here we have two core groups to woo, (1) potential Hy users and (2) researchers/hackers who can get into Hy language development right away. Kodiologist very wisely said "send developers to conferences" -- if you can get them to give talks this would be GREAT. It also gives us focal points for fundraisers that obviate the need to structure an org for the time being.

Those are some random droppings from what might be something organized with spreadsheets and slide decks and organizational structure proposals after lots of data gathering yadda yadda yadda -- I could, in a professional (even if donated) capacity look into what open source funders such as NumFOCUS are doing and prepare everything.  But in the short term, Kodiologist has already identified a critical point.

Existing Hy hackers (who are they? what are they doing? can we organize a spreadsheet?)  could list relevant conferences (maybe one in the Python world and one in the Clojure world) and make a reasonable budget where they get to stay in a nice hotel. Then these can be converted into a fundraiser.  This will also work to signal to passersby that the project is not dying (which is important -- users outside a hobby context bear some significant risk in adopting a new language in this state.)

For a very first step, what's the order of magnitude cost of sending someone to a conference? Closer to $500 or to $2500?

---
You can probably tell I'm very excited about Hy. It has everything to succeed -- usually with tech adoption, collective switching costs are a bitch, but here switching costs have to be at best borne by an individual who can keep working in a Python team.

**Comment by Kodiologist** [comment]
I guess we're just not big enough to do much with money, or make enough that we could do more, and I don't foresee this changing. When we release Hy 1.0, will we become a big deal, or at least a big deal by the standards of obscure programming languages? Maybe, but I wouldn't hold my breath, and we can cross that bridge when we come to it.

I know that @paultag is at least paying for our domain name and @allison-casey is paying for the AWS time to run Try Hy. I suspect the costs are low enough that it's not even worth the bother of collecting donations for them. If either of you disagree and want to do a little fundraising, let me know. Failing that, I think we should put this aside until and unless Hy gets big enough for us to worry about it.

**Comment by paultag** [comment]
I agree; no worries here anyway - I'd be delighted to see donations in Hy's name to the OSI, FSF or other reputable community-driven not for profit working on defending the free and open source software community, though! That's just my personal opinion, though!
