### ISSUE TITLE
update tutorial to use new language version

### ISSUE THREAD

**Issue by gilch** [hylang/hy#971]
Hy is changing with the Grand Language Cleanup. The tutorial must be updated to reflect these changes in Hy.

**Comment by martinakcsilla** [comment]
Which part of the tutorial needs updating? A quick skim through it doesn't reveal anything obvious, except maybe two examples:

* The `(defclass)` example where `--init--` has an explicit `None` at the end, which could be omitted.
* An `apply` example in the "Hy <-> Python interop" section, where the named arguments could use keywords instead of strings.

Is there anything else? The rest of the syntax changes appear to be reflected in the tutorial too.

**Comment by gilch** [comment]
I think I saw extra brackets in a `with`. The style guide following the tutorial also has extra brackets in a `let`. We should probably work through the pre-reference part of the docs (Quickstart, Tutorial, Style Guide) with a repl to make sure everything still works. I doubt we'll catch everything just by looking.

Some of the pending Grand Language Cleanup changes may break this again, so maybe we should wait until that's completed.

**Comment by Kodiologist** [comment]
I've verified that the tutorial is currently up to date. In the future, the code samples there, like elsewhere in the documentation, should be checked automatically (#1019).
