### ISSUE TITLE
Docs for destructuring?

### ISSUE THREAD

**Issue by ghost** [hylang/hy#978]
I'd add it myself, but I dunno where it would fit.

Looking at the [doc indexes](http://docs.hylang.org/en/latest/language/index.html), I do not see an obvious place for it.

(Searching for "destructuring" in the docs yielded [no results](http://docs.hylang.org/en/latest/search.html?q=destructuring&check_keywords=yes&area=default))

**Comment by kirbyfan64** [comment]
Do you mean argument destructuring (like `(defn f [[a b]] (+ a b))`) or value destructuring (like `(setv [a b] c)`)?

**Comment by endrebak** [comment]
Function, I guess that is argument destructuring.

**Comment by berkerpeksag** [comment]
Perhaps we can add a new "Hy Cookbook" chapter to docs.

**Comment by gilch** [comment]
Maybe a cookbook is not a bad idea once we finish the Grand Language Cleanup, but before that it's premature, since we'd have to update it with every change. This will be hard enough as it is. I don't think we've updated anything in `eg/` for a while.

A cookbook is not a substitute for a basic reference. It's too hard to find more basic things like "how destructuring works" if the recipes are things like "how to use Hy with Django".

Hy depends a lot on Python's documentation. It would be a waste of time to reproduce the documentation for Python's standard library, for example. But perhaps we could make more explicit references to Python's documentation where appropriate.

**Comment by Kodiologist** [comment]
This feature was removed in #1590.
